/* ============================================================
   Phlebotomist Consumable Verification - script.js
   ============================================================ */

'use strict';

// ============================================================
// CONFIGURATION — paste your Google Apps Script web app URL here
// ============================================================
const GOOGLE_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbxIWxZuJSe8dPzXqfnDxdaPwYjb5eCjejTh4ZhSQQwB4_Mg-AMJ0b_v3TDUpUyA76Frhw/exec';

// ============================================================
// MASTER DATA (from Excel: Drop-Down List sheet)
// Key structure: masterData[district][campType][jasMas][teamNo] = teamName
// ============================================================
const masterData = {"WASHIM":{"MMU Camp":{"ANIKET  NILKANTH JANBANDHU":{"MMU0006735":"NIKITA MADHAV GIRI,TAI AMBADAS VAIDYA"}},"DOOR TO DOOR":{"Yogesh Sanjay Hagawne":{"D2DWASWAS6757":"MOHD ABUZAR MOHD TASLEEM NANGIWALE,ASIF RAMJAN KALIPIRWALE","D2DWASWAS6564":"SWAPNIL  UDDHARAO JADHAV,DNYANESHWAR MADHAV MAGAR","D2DWASWAS6526":"RAHUL  DAMODAR MANVATKAR,KULDIP   YADAV","D2DWASWAS5863":"RITESH BRANHADEO RATHOD,RANJIT PUNDALIK RATHOD","D2DWASWAS5048":"REHAN   SHAH,Sohail Rashid Shah","D2DWASWAS3457":"VAIBHAV  DESHMUKH,GOPAL RAMESH DHONGADE","D2DWASKAR1121":"Mohsin  Basheer Shaikh,Mustaqueem shah Asad Shah"}}},"SANGLI":{"MMU Camp":{"Jaydeep  Gurav":{"MMU0006719":"Ketaki Santosh Mahalingpure,Kirti Bhimsen Awale"}},"DOOR TO DOOR":{"Sahil  Pathan":{"D2DSANSAN832":"AMAR   PATIL,SNEHA  Deepak SHIKALGAR","D2DSANSAN6774":"Sushant  Prakash Landge,Ratan Ananda Hirave","D2DSANSAN5290":"Pournima Rajendra Sathe,ABHIJEET   GEND","D2DSANSAN400":"Pratiksha Rajaram patil,Shubhangi  Ananda jamdade","D2DSANSAN399":"Sachin  Bramhanath rendalkar,Ujjawala  Sachin rendalkar"},"PRIYANKA  BASGONDA MAGDUM":{"D2DSANSAN6789":"PRASHANT BHAIRAPPA NARUTE,ASHARANI KALLAPPA KOTYAL","D2DSANSAN6788":"PRAJWAL  BASGONDA MAGDUM,SADASHIV MAHADEV KOTTALAGI","D2DSANSAN6787":"SUREKHA SIDDU MALI,PRAGATI DAYANAND KATE","D2DSANSAN6786":"SHASHIKALA SIDRAYA BIRADAR,Laxmi Bhagawat Gejage","D2DSANSAN6392":"AMIR RAMAJAN NADAF,ASLAM ADAM PATEL","D2DSANSAN6389":"ASIM ALLABAKSH NAIK,BIRAPPA RAVASAHEB HATTIKAR","D2DSANSAN6164":"Nakusha Sitaram Garale,Somanath Bajarang Garale","D2DSANSAN6162":"Sachin  Kale,ROHIT RAVASAHEB KOLI"},"Nikhil  Mahesh Shah":{"D2DSANSAN6782":"Seema  Nilesh sangavkar,Pramod Laxman Buchade","D2DSANSAN6646":"OMKAR ANIL YADAV,KRUNAL  SAGAR MORE","D2DSANSAN6609":"PANKAJ  SURESH SOUDAGAR,Aniket  Shankar Kotiwani","D2DSANSAN6553":"CHANDANI MUMTAJ ILAHI JAMADAR,KAJAL Navnath LOKHANDE","D2DSANSAN6407":"AKSHTA  VIJAY KOLI,Monika Shravan Chafe","D2DSANSAN6167":"Moin Nazir Shaikh,Rahul Hanmant Landage","D2DSANSAN6083":"GANESH  GORAKH KADAM,Nikita Gorakh Kadam","D2DSANSAN3635":"Sarjerav  Subhash sutar,Gouri  Vijay Gote"},"AKASH ANIL PATIL":{"D2DSANSAN6773":"Ananda  Madhukar Burud,SWAPNIL  SANJAY KHOT","D2DSANSAN3937":"Sachin  Jaywant Katnale,RAHUL  KHARAJE","D2DSANSAN3769":"NIHAL  ALTAF TAMBOLI,SAGAR  DHANAJI KAPARE","D2DSANSAN3001":"Tukaram Dattatray Kengar,Akshay Netaji Mane","D2DSANSAN1452":"Ratish  Dadasaheb Zagade,Vishal  Vidyanand Biranagi"},"SUNITA SUNNY SONUDADE":{"D2DSANSAN6750":"JAYSAN  KANDLE,Sakib  Mahammadhusen Sayyad","D2DSANSAN6594":"Aniruddha  Shrikant Kshirsagar,Vijaysingh Dilip Sherikar","D2DSANSAN6119":"SAKSHI  DIPAK BHOSALE,Siddharth Sanjay Kamble","D2DSANSAN6118":"Onkar Ramchandra Jadhav,NIHAL  KHOT","D2DSANSAN4243":"ARPANA  MANOJ GAIKWAD,DINESH  KAMBLE","D2DSANSAN3983":"VISHAL  VINAYAK GAVANDI,OMKAR  TUKARAM MORE"},"Ashwini Balasaheb Patil":{"D2DSANSAN6662":"SUJAL RAMA RANBHARE,MRUNMAYI RAJKUMAR DEGAONKAR","D2DSANSAN6638":"Muddasar   AbdulMajid Soudagar,SHAMA KADAR MUJAWAR","D2DSANSAN6406":"PRATIK  ASHOK PAWAR,AKSHADA  KALLI","D2DSANSAN6359":"Tejaswini  Tataoba Heralage,Sushil Subhash Dange","D2DSANSAN5879":"SONALI  KAMBLE,Chaitanya   Waghmare","D2DSANSAN5694":"sandesh  nanasaheb koli,SARIKA ATMARAM METKARI","D2DSANSAN5390":"Suraj   Madhukar JADHAV,RANJIT   SHINDE","D2DSANSAN4026":"PRATIK  CHAUGULE,PRATHMESH  CHOUGULE"},"SUNNY  TANAJI SOUNDADE":{"D2DSANSAN6089":"Rushikesh  Pandurang Chavan,Vaishnavi Gunaji Kiramate","D2DSANSAN5959":"PRASHANT  MULIK,MANSING MOHAN MANE","D2DSANSAN5958":"SHREYASH DEEPAK KALYANI,AKSHAY  SURESH BHOSALE","D2DSANSAN5096":"SANKET  NALAWADE,CHETAN   JADHAV","D2DSANSAN2568":"AMIT  SURESH SOUDAGAR,ARTI  ANANDA BHANUSE","D2DSANSAN2559":"YOHAN  JAYLAL AWALE,DIPALI  SUNIL MORE"},"Shamir  Adam Mulani":{"D2DSANSAN5479":"SANTOSH  KRUSHNAT KHOT,NITIN  KHOT","D2DSANSAN5478":"Swapnil Arjun Raskar,AVDHOOT  SHIVMARE","D2DSANSAN4179":"RANJIT  SATISH VIRKAR,SWAPNIL  RASKAR","D2DSANSAN4178":"MAHAMMAD SAAD  MUBARAK JAMDAR,Sagar PATIL Sadashiv","D2DSANSAN4170":"DAUD  ISAK MOKASHI,SHAKTI  KAMBLE","D2DSANSAN4169":"Rupesh  Rajaram Khole,Shambhuraje Anandrao Jambhale","D2DSANISL698":"RAHUL ASHOK KAMBLE,ABHIJIT  YUVRAJ KAMBLE","D2DSANISL410":"ASLAM BASHIR PATHAN,SOMNATH  PRAKASH PHUTANE"}}},"SOLAPUR":{"MMU Camp":{"GANESH  TUKARAM BHOSALE":{"MMU0006697":"SANSKAR   JADHAV,CHANBASAPPA SHRISHAIL KUDARIKANNUR"}},"DOOR TO DOOR":{"AYAN  RIYAZHUSAIN SHAIKH":{"D2DSOLSOL6725":"DAYANAND  MALLAPPA BIRAJDA,GANESH  DHAVALE","D2DSOLSOL5950":"DIPAK BIBHISHAN KHOT,SACHIN VISHNU GHADGE","D2DSOLSOL5755":"BALKRUSHNA DADASO KABADE,ONKAR MALLIKARJUN MALI","D2DSOLSOL5115":"Ashikesh  Dilip Gavali,SATYAJEET   MANE","D2DSOLSOL4680":"AKIL  SHAKHIL MUJAWAR,RAJESH   METKARI","D2DSOLSOL3785":"Husen  Mahammad Mujawar,RIYAZ  MULANI"},"Meenakshi  Babu Udase":{"D2DSOLSOL6643":"SHOAIB  KASIMSAB SAYYED,MD RASOOL RABBANI SHAIKH","D2DSOLSOL5491":"NAVNATH   DOMBALE,SACHIN   LAWATE","D2DSOLSOL4049":"KISAN  DNYANESHWAR BANKAR,SAURABH  SAHEBRAO OWAL","D2DSOLSOL3819":"ANIKET  SOPAN MADNE,TEJASKUMAR  POPAT MANE","D2DSOLSOL3074":"SHIRISH  ASHOK BHANDARI,sunny  Ramchandra Abute","D2DSOLSOL2809":"JUNAID NAEEM SHAIKH,MOHSIN  MUSTAK IRKAL","D2DSOLPAN2869":"PRATIKSHA  SANJAY OWHAL,SANJAY  OWAL"},"Sandhya  Ramakant Jadhav":{"D2DSOLSOL6593":"SANIYA   MULLA,MONIKA   VISHWANATH UPASE","D2DSOLSOL6585":"RUSHIKESH  LAVAND,Kalpesh   Lawand","D2DSOLSOL6584":"AJAY  SARTAPE,SAGAR   SONAVALE","D2DSOLSOL4685":"Akshay  Machindra Salunkhe,Vidya Akshay Salunke","D2DSOLSOL4015":"AKSHAY  DATTATRAYA AWATE,DHIRAJ  SHENDAGE","D2DSOLSOL3232":"Somanath   Dashrath Nile,Birudev Balu Nile"},"TUSHAR  BAPURAO MARKAD":{"D2DSOLSOL6473":"YOGESH   GIRI,RIYAZ SALIM SHAIKH","D2DSOLSOL6472":"MANIK  RAMESH KAGANE,VISHAL AMBRUSHI MADAKE","D2DSOLSOL5814":"ISAK KAYYUM FARAS,PRASHANT SHIVLINGAPPA VHANCHENJE","D2DSOLSOL5754":"VISHWESH VIJAYKUMAR TATE,VIKARAM  DILIP GAWALI","D2DSOLSOL5451":"AMAN   BAGWAN,SHRISHAIL   JAMDANDE","D2DSOLSOL3816":"Shrimant  Ankush Nagargoje,HANUMANT  ANKUSH NAGARGOJE","D2DSOLSOL3280":"MAINA  VIJAY WAGHMARE,CHUNGIWALE SANIYA NILPASHA","D2DSOLBAR3199":"KIRSHNA  RAMESHWAR CHOURE,TANAJI BHARAT LANDAGE"},"KSHITIJA RAVINDRA SHIRSODE":{"D2DSOLSOL6061":"MUAAJ  SHAIKH,VAIBHAV  SHINDE","D2DSOLSOL5951":"ATUL JASWANT SOLANI,SAI BALASAHEB NAVALE","D2DSOLSOL5724":"AKSHAY  VITTHAL HAKE,AHAMAD  MUJAWAR","D2DSOLSOL5723":"VIKRAM  PRADIP SARWADE,SHUBHAM   SARWADE","D2DSOLSOL4252":"SHIVRAJ   SWAMI,SARTHAK   HARIHAR","D2DSOLPAN2881":"NISHANT NAGNATH KULKARNI,KESHAV  BABAN TONDALE","D2DSOLPAN1370":"ASHITOSH SUDHAKAR TELI,Pravin  Sharad More"},"TAYYABA  PATEL":{"D2DSOLSOL5952":"JUBER   MUJEED,VISHAL YUVRAJ WELFODE","D2DSOLSOL5591":"NADIM   SHAIKH,PRAMOD   SONAWANE","D2DSOLSOL4758":"Ahemadali Inayat Alishaikh,SABIR  BADEGHAR","D2DSOLSOL4559":"MAHESH     CHOUGULE,NITIN   GADAGE","D2DSOLSOL4129":"RAJENDRA  KAMBLE,SANGHANAND  GAIKWAD","D2DSOLSOL4016":"TOHID  MULLA,JEBA MD  NADAF","D2DSOLSOL3669":"FAISAL  BAGWAN,KAILAS  NANAVARE","D2DSOLSOL3186":"JAYVANT SHANKAR ROHITE,REHAN CHANDSAB INAMDAR","D2DSOLSOL2507":"Javed   Shaikh,NURODDIN  MAINUDDIN TAMBOLI"},"NA":{"D2DSOLSOL3218":"Tejas Gopal Bhasme,Prasad Bhimrao kokate"}}},"LATUR":{"MMU Camp":{"ROHAN  SAWANT":{"MMU0006682":"SANDIP  WAGHCHOURE,Taleb  Yunus Shaikh"}},"DOOR TO DOOR":{"Shambhu Datta Shinde":{"D2DLATLAT6687":"SHIDHART SHIDESHWER SURYVANSHI,BALAJI SADANAND PANDIT","D2DLATLAT6434":"RAHUL VITTAL GULBILE,GAJANAN PARAKASH MANE","D2DLATLAT6068":"YOGESH   DASARE,SALBA BALAJI JADHAV","D2DLATLAT5371":"Juned  Rashid Shaikh,SUHEL MOHMMED KHAN"},"Somnath  Bhimrao Kamble":{"D2DLATLAT6674":"Prashant  Lahu Chame,REHAN  PATHAN","D2DLATLAT5787":"ARUN  KAMBLE,SUVERNAPRABHA ARUN KAMBLE","D2DLATLAT5731":"SWAPNIL   BHALERAO,ADINATH   MANE","D2DLATLAT5730":"Manoj  Vasant Rathod,DIPAK VILAS PAWAR","D2DLATLAT5729":"MAHESH   KSHIRSAGAR,MANOJ RAVIKIRAN MUSANDE","D2DLATLAT5728":"PRATIKSHA  SALVE,SAKSHI DATTA SONWANE"},"VIKI  HANMANTE":{"D2DLATLAT6445":"SAGAR  GULAB PANDIT,OM DASHRATH RATHOD","D2DLATLAT6074":"VINOD  BHALERAO,BALKRUSHNA JAGANNATH SHEWALE","D2DLATLAT6069":"ABHIJIT SHIVSHANKAR JAMBHALE,PRATIK PRADIPKUMAR HAMBIRE","D2DLATLAT5065":"SAYYAD SOHEL SATTAR,SAHIL   SAYYAD","D2DLATLAT4293":"KAMBLE SANGHARSH  GOROBA,PRITAM   SABLE"},"Rohan  Kendre":{"D2DLATLAT5856":"Mahesh  Suryakant Sonwane,SHUBHAM LIMBRAJ MAKUDE","D2DLATLAT2309":"VISHNU  MARUTI RATNAPARKHE,KALPESH  GOVIND SARWADE","D2DLATLAT2256":"Adesh Balaji Shinde,ADITYA BALAJI SHINDE","D2DLATLAT1535":"Tabrez  Adam Sayyad,Fardin  Fayyazoddin Shaikh"},"Shreyesh   Vijay Khandagale":{"D2DLATLAT5677":"SALIMODDIN NIJAMODDIN SHAIKH,RAMCHANDRA RAJKUMAR KERURE","D2DLATLAT5553":"TAYYAB   SHAIKH,ASHIT   KORDE","D2DLATLAT5301":"PRADNYA   BHAGWAT,MONIKA   KHANDAGALE"}}},"NANDURBAR":{"MMU Camp":{"Umesh Chhotu Rathod":{"MMU0006632":"Shalini  Ravindra Gavit,Tushar   Karamsing Valvi","MMU0005790":"Ashwini Dilip Parmar,Laxmi Jamsing Ravtale"}},"DOOR TO DOOR":{"Satish Lotan Pimpale":{"D2DNANSHA6258":"Gorakh Driver Pawar,Ankita  Dileep Jadhaw","D2DNANSHA6257":"NITESH AAPSING PATLE, Sandip  Tiger Pawar","D2DNANSHA6107":"Ravita Dumana Pawara,Sujit Santosh Jadhav","D2DNANSHA5709":"Harishchandra Lagan Sule,Popya Subhash Pawara","D2DNANSHA5702":"Vishal Bahadur Pawara,Rohit Bhaurao Samudre","D2DNANSHA5463":"Pushapanjali Pankaj Patil,Akash Chaudhari Pawara","D2DNANSHA5262":"Bavsar Ishwar Pawara,Rahul Suklal Jadhav","D2DNANSHA4431":"Rahul Dhnajya Pawara,Laxman Akash Bhandari"},"Digambar Ishwar Patil":{"D2DNANNAV6531":"Rohit Raju Gavit,Nikhil Hiralal Nikam","D2DNANNAV5793":"Pravin Latish Padvi,Darshan Vijay Bagale","D2DNANNAN6489":"Eshwar Vanya Gavit,Sushila Ishwar Gavit","D2DNANNAN5703":"Sanjay Bharat Gavit,Kaif  Daud Shaikh"},"Manoj Nana Patole":{"D2DNANNAN6756":"AJAY TARSING NAIK,Roshan Ramsing Thakare","D2DNANNAN6696":"Dipesh Naresh Mahajan,Gokul Paramsing Naik","D2DNANNAN6678":"Ramakant Bhila Dhangar,Kapil Thansing Salunkhe","D2DNANNAN6408":"Rajendr Tapiram Pawara,Sushmita Dohanya Pawara","D2DNANNAN6317":"Shubham Sahebrao Shinde,Siddhesh Chamarya Vasave","D2DNANNAN5550":"DURGESH ANIL BHAVASAR,Mangesh  Jayram Patil"},"KALPESH SANJAY RAJPUT":{"D2DNANNAN6745":"Gopal Harinand Padvi,Rakshvardhan Bajirav Tadvi","D2DNANNAN6744":"Ashish Sanjay Pawar,Khemraj Bhatu Ajage","D2DNANNAN6743":"Harsing  Moyala Pawara,Suraj Dilip Pawara","D2DNANNAN6591":"Manish  Kishor Pawar,Ranjana  Ratan Gavit","D2DNANNAN6383":"Akshay Ravindra Shinde,Umesh Sanjay Chaudhari","D2DNANNAN6031":"MANOHAR GORAKH PATIL,Amol Shailesh Valvi"},"Soham Gaimalsing Padvi":{"D2DNANNAN6633":"ROSHAN SURESH SHINDE,Shrinath Pandit Jadhav","D2DNANAKK6742":"Ashok Noblya Tadvi,Sandip Saysing Vasave","D2DNANAKK6741":"FATTESING  RAJESING VASAVE,Pravin   Soma Navej","D2DNANAKK6737":"Mayur Anil Savale,Saurav Anil Shimpi","D2DNANAKK6736":"Shreyash Sanjay Padavi,Aniket Kishor Valvi","D2DNANAKK6197":"Nilesh Ganpatsing Vasave,Ajay Shamsing Valvi","D2DNANAKK6123":"Suraj Shriram Patil,Kunal Vaikunth Bhavasar","D2DNANAKK6116":"Rajendra Kagada Vasave,Govind Makatya Vasave","D2DNANAKK4754":"GULABSING  ISHWAR VALVI,Narendra Surta Vasave"}}},"THANE":{"MMU Camp":{"Nagesh Bhujinga Patil":{"MMU0006631":"Harshada  Sanjay Raut,Divya Sanjay Raut"}},"DOOR TO DOOR":{"Nagesh  P":{"D2DTHATHA6049":"Ziya Sayeed Khan,Mohin  Mainuddin Khan","D2DTHATHA5966":"AQDUS  IMMAMUDDIN SHAIKH,ALMAS  NISAR AHMADPA","D2DTHATHA5664":"MOMIN ALHERAMOHD ZAFAR,Hafsa Bano Hyder Ali Momin","D2DTHATHA5658":"Namrta Kantaram Dinkar,Pranali  Ramdas Mojad"}}},"SATARA":{"MMU Camp":{"AMIT  GHADGE":{"MMU0006623":"SHIVANJALI SANJAY SATRE,Prachi  Hagavane"}},"DOOR TO DOOR":{"PRIYANKA  THORAT":{"D2DSATSAT6783":"HARSHADA DADASO KACHARE,POONAM RANJIT BAVADEKAR","D2DSATSAT6488":"RUTUJA  BHARAT CHAVAN,PRAFULLA  BANSODE","D2DSATSAT6486":"USHA  SHINDE,VISHKHA  CHIBADE","D2DSATSAT6485":"POOJA  RAMESH DINDE,Poonam Sudhakar Thorat","D2DSATSAT6340":"SNEHAL  BABASO KAKADE,SAGAR   BADEKAR","D2DSATSAT6215":"RADHIKA  VIBHUTE,Nayana Nilkanth Thete","D2DSATSAT6214":"ARCHANA  SURESH SALUNKHE,Anuradha Pratap Shewale","D2DSATSAT6153":"PRATIKSHA  THORAT,Sonali Subhash Pawar"},"SONAM  GANESH DESAI":{"D2DSATSAT6708":"YASHRAJ ASHOK GARDE,NIKHIL KIRAN VICHARE","D2DSATSAT6703":"TANJILA  BAGWAN,ANJALI  YADAV","D2DSATSAT6621":"Sahil Rajendra Jadhav,Durvesh Vijay Dhekale","D2DSATSAT5876":"MAHESHWARI  BADEKAR,MADHURA   DIXIT","D2DSATSAT5656":"Yash Prabhakar More,SAMEER BHAGWAN GHODAKE","D2DSATSAT2570":"AMAY  ANIL KUNDALKAR,NIKHIL   BHANUDAS KSHIRSAGAR"},"DHANASHREE SANGARAM GAIKWAD":{"D2DSATSAT6694":"Akanksha  Arun More,PRATIKSHA  LOHAR","D2DSATSAT6693":"AKANKSHA MAHENDRA PAWAR,RUSHALI DATTATRAY SHINDE","D2DSATSAT6657":"KASTURI HARISH MOHARKAR,PRATIKSHA MAHADEV LAKHE","D2DSATSAT6622":"Vrushali   Jadhav,Suyog Sachin Yadav","D2DSATSAT6608":"SURAJ SHIVAJI DONGARE,SWAPNALI ROHAN JAGTAP","D2DSATSAT6513":"RAJENDRA CHANDRAKANT SHINGADE,RAHUL JAGANNATH KHADE","D2DSATSAT5309":"Pallavi  Tukaram Yadav,SNEHAL   VITTHAL JADHAV","D2DSATSAT5308":"TANUJA  DUTAL,Madhavi Ramesh Madane"},"PRUTHVIRAJ  PANDURANG YADAV":{"D2DSATSAT6410":"Ravindra  Sakharam Bansode,SACHIKET   DHANAVADE","D2DSATSAT6329":"Mahesh  Bhagwat,BHARAT   KAMBLE","D2DSATSAT5040":"SANJIVANI  SURESH DESHMANE,SHRADHA  YADAV","D2DSATSAT4612":"ADITI  DATTATRAY NIKAM,JAYRAJ  JADHAV"}}},"BULDHANA":{"MMU Camp":{"SACHIN  SANJAY JADHAO":{"MMU0006597":"ASHWINI NINAJI PACHPOL,SHAHU BHAGWAN RAJMANE"}},"DOOR TO DOOR":{"RAJU  DHONDU BACHATE":{"D2DBULMEH509":"VITTHAL  ASHRU GAIKWAD,RAHUL  JANARDHAN UKANDE","D2DBULMEH507":"NITESH  RAMESHWAR RAUT,POOJA PARMESHWAR BACHATE","D2DBULBUL6724":"POOJA PARAMESHWAR SONUNE,POOJA MANOHAR DUTONDE","D2DBULBUL6723":"ANKUSH NANDA DHONDGE,ANIKET DINKARRAO GADEKAR","D2DBULBUL6426":"GANESH  MANOHAR WAGH,MAHESH AUN BHANDURGE","D2DBULBUL5172":"SATISH  MHALASANE,SHAUKAT   MOHAMMAD"},"SHIVANI NIVRUTTI AVCHAR":{"D2DBULBUL6726":"Prem Ganesh Pahade,Rushikesh Rajendra Wagh","D2DBULBUL6399":"Vishal Murlidhar Asolkar,Ashish Tejrao Wankhade","D2DBULBUL6316":"Amoling Darbarsing Ingale,Akshay Anilrao Chavan","D2DBULBUL6315":"SATISH DADARAV DABHADE,Buddhabhushan Vilas Dabhade","D2DBULBUL6303":"Rahul Laxman Dabhade,Sachin Shriram Dabhade","D2DBULBUL6302":"Nakul Baburao Ingale,Bhuvanesh Pradip Chavan"},"SHAHEBAJKHA  RASHIDKHA PATHAN":{"D2DBULBUL6714":"JIVAM  VINOD MORE,RUSHIKESH SAMBHAJI SONUNE","D2DBULBUL6713":"Mayur Rameshwar Kankal,Vedant Kailas Kashikar","D2DBULBUL5743":"ARBAZ KHAN ASLAM KHAN,MOHAMMAD ABID MOHAMMAD JAVED","D2DBULBUL5295":"SHUBHAM  SAWALE,ANSARI  QUAMROSH","D2DBULBUL5163":"RAM RAJESH RATHOD,ANKIT  KADUBA JADHAO","D2DBULBUL4393":"NASEEM KALEEAM SHAIKH, ZAKIR  YUNUS SHAIKH"},"Amol  Ganesh Khodke":{"D2DBULBUL6405":"Sufiyanuddin Gaffaroddin Patel,Rehanuddin  Gafaruddin","D2DBULBUL6398":"Umesh   Wakode,Aditya  Pargharmor","D2DBULBUL6240":"SANDIP PRAKASH INGALE,Kunal Supada Wagh","D2DBULBUL5578":"SHUBHAM  MOHAN KHEDKAR,Yogesh   Ghate","D2DBULBUL5046":"AKSHAY  NARAYAN DUTONDE,Nagesh  Parashram Dutonde","D2DBULBUL5045":"Vijay  Bhagwan Sontakke,Ankit  Khodke","D2DBULBUL5044":"Ranjit  Sadashiv Solanke,Shubham  Sadashiv Solanke"},"SUHAS GAJANAN SHINDE":{"D2DBULBUL5576":"AMOL RAMESH WAGHMARE,TUSHAR  HARIDAS RASAL","D2DBULBUL5496":"BHUSHAN   JAISWAL,Zakir Mahemood Shaikh","D2DBULBUL5296":"PRATIK GAJANAN JADHAV,PAVAN   PARIHAR","D2DBULBUL5047":"BHAGYSHRI KOSHOR HALDE,KISHOR  ARJUN HALDE","D2DBULBUL4804":"UMESH   SAPKAL,SIDDHESHWAR   PAWAR","D2DBULBUL3289":"DHIRAJ SHESHRAO JADHAO,SIDDHESHWAR  JAGANNATH SOLANKI"}}},"RAIGAD":{"MMU Camp":{"Amol  Dashrath Dahale":{"MMU0006592":"Sakshi  Sudhir Patil,Jyoti Manik Chinnarathod"}},"DOOR TO DOOR":{"Rajendra Sundar Kadu":{"D2DRAIMAN3540":"SANJIT  YETU GAIKWAD,SHEKHAR MARUTI KALAMKAR","D2DRAIKHA6230":"Rupali  Rama Pawar,Anashree Vijay Bhonkar","D2DRAIKHA6176":"Sonali Prabhakar Mangle,Adarsh Deepak More","D2DRAIKHA6050":"Pooja Vishal Mahadik,Vanita Vijay Choudhari"}}},"PALGHAR":{"MMU Camp":{"Nilesh  Gupta":{"MMU0006581":"Sunil Ananta Ghosha,Mamata  Dilip Mor"}},"DOOR TO DOOR":{"Ankush Lahanu Tokare":{"D2DPALJAW6483":"Sarika Subhash Bhavar,Ajit  Chandrakant Khurkute","D2DPALJAW6454":"Payal Sunil Mahale,Bhavana Bhau Mahale","D2DPALJAW5823":"Arun Vinayak Chaudhari,Swapnil  Shankar Khale","D2DPALJAW5822":"Suraj Vasant Dighe,Vishwanath Sadashiv Khurkute","D2DPALJAW5817":"Akshay  Suresh Umbarsade,Devendra Ravaji Digha"}}},"KOLHAPUR":{"MMU Camp":{"Nilesh  Dhage":{"MMU0006469":"SHOEB   PATEL,Sonali Bajirao Kamble"}},"DOOR TO DOOR":{"Rutuja   sutar":{"D2DKOLKOL825":"AMAN  SHABBIR BANDWAL,RUSHIKESH  DEVAPPA MALAVI","D2DKOLKOL6503":"Pallavi Shashikant Ghatage,Aishwarya Shivam Satpute","D2DKOLKOL6036":"Nageshwari Aniruddh Hiremath,Manasi Avinash Galande","D2DKOLKOL5968":"Anil  Maruti Harale,SHUBHAM   PAWAR","D2DKOLKOL5847":"Sunita Pravin Patil,Kajal Samrat Patil","D2DKOLKOL5844":"Ganesh   Govind Kumbhar,Sanika Ganesh Kumbhar","D2DKOLKOL4894":"Amrut   Sutar,sandesh   patil","D2DKOLKOL4279":"Prathmesh   Bhimraokamble,Prathamesh   kamble"},"Ruturaj Kundlik Durgule":{"D2DKOLKOL6753":"Snehal  Patil,JUVERIYA FIROJ MULLA","D2DKOLKOL6752":"lalita   lohar,PRATIKSHA TANAJI BIRANJE","D2DKOLKOL6751":"Namrata   Kamble,PRIYANKA   ASABE","D2DKOLKOL6614":"Deepak  Bamblade,Pratiksha   Kamble","D2DKOLKOL6613":"RUSHIKESH  AREKAR,Mukta Shankar Hanbar","D2DKOLKOL6612":"Archana Sagar Dalavi,Sushma Subhash Hadapad","D2DKOLKOL6287":"GANESH  TUKARAM PATIL,POOJA  PATIL","D2DKOLKOL6104":"Sanket Prabhakar Jadhav,Kunal Rajaram Savant","D2DKOLKOL5674":"ADITYA BAJIRAO KUMBHAR,Pooja   Tarale","D2DKOLKOL5651":"Samruddi Kallappa Donkari,Aishwarya Yallppa Naik"},"Surendra  balavant Nangare":{"D2DKOLKOL6729":"Ganesh  Krishnat Pandav,NIHAL DASTGIR BANDWAL","D2DKOLKOL6016":"SHANKAR  RATHOD,LAXMI VITTTHAL AMKAR","D2DKOLKOL5983":"RAJ  PRAKASH SANGALE,Komal   Buva","D2DKOLKOL5690":"Shreya  Arun Malave,KEDAR DIPAK PATIL","D2DKOLKOL4968":"MAHADEV  YUVRAJ PARITKAR,PADMASHREE   PARITKAR","D2DKOLKOL4967":"Sarang   Shevale,Pradip   Chavan","D2DKOLKOL3585":"Sandip  Sudarshan Sawant,Ashok  Bandu patil","D2DKOLKOL279":"SOHEL   JAMADAR,SANIKA   DABADE","D2DKOLKOL2733":"Sahil  Babasaheb Jamadar,Sakshi  Sanjay Dorkar","D2DKOLKOL1120":"POONAM   VADINGEKAR,KAVITA   KATALE"},"SANDEEP MARUTI CHAVAN":{"D2DKOLKOL6715":"Sagar  Baburao Jondhalekar,Shivani   Patil","D2DKOLKOL6639":"ANKITA ANKUSH DAWAR,SHRUTIKA RAMCHANDRA CHUYEKAR","D2DKOLKOL5990":"Yuvraj  ramesh chougule,PRATHAMESH MOHAN KAMBLE","D2DKOLKOL5864":"Pooja  Hemant Kamble,Samruddhi   Kelosakar","D2DKOLKOL4933":"yogita   Khot,PUNAM   DESAI","D2DKOLKOL4896":"Akanksha  Ajinkya Kalindre,SAKSHI  ANIL CHOUGULE","D2DKOLKOL4878":"Dipali  Ashutosh Kamble,Ashutosh  Yashvant Kamble","D2DKOLKOL4428":"rushikesh  kholambe,gouri   kholambe"},"DUMMY  PM":{"D2DKOLKOL6521":"test PHLEBO HLLONE,test PHLL TWIO"},"DIGAMBAR VIJAY AIWALE":{"D2DKOLKOL6500":"PRAMOD RAVASAHEB CHOUGULE,Kenchamma Pramod Chougule","D2DKOLKOL6498":"PRAVIN SURESH BHORE,SHUBHAM LAXMAN BHORE","D2DKOLKOL6270":"OMKAR  SURESH KAMBLE,Rohit Anil Wadkar","D2DKOLKOL6241":"AKSHAY  ARVIND PATIL,RANJEET  AABAS AKURDE","D2DKOLKOL5929":"Amit  Sambhaji Patil,Balraj Jitendra Patil","D2DKOLKOL3713":"Avadhut  Athavale,Swati  athavale","D2DKOLKOL2807":"Malati  Nitish Kamble,Nitish  Rangarav Kamble"},"Vijay  Suryawanshi":{"D2DKOLKOL6301":"Uday  Kumar Pawar,Asif  Ajit Faras","D2DKOLKOL6300":"Rushikesh  Umesh Patil,Sanket  Babaso Patil","D2DKOLKOL6015":"Prajwal DILIP Shinde,SHUBHAM CHANDRAKANT PATIL","D2DKOLKOL6014":"Anagha  Bailkar,Rachana Rajan Patil","D2DKOLKOL5278":"Akash   Desai,Omkar   jingare","D2DKOLKOL5277":"ROHAN  RANGRAO PATIL,VIVEK   SUTAR","D2DKOLKOL5087":"Akshay Sardar Savekar,Abhishek   Wakarekar"},"AMOL DINKAR PATIL":{"D2DKOLKOL6055":"AKSHAY  PATIL,SWAPNIL SANJAY PATIL","D2DKOLKOL6028":"ABHINANDAN   BAGADI,Dhiraj Bharamana Patil","D2DKOLKOL6004":"TANAJI    TALWAR,Madhuri Vijay Patil","D2DKOLKOL5588":"ANIKET TANAJI BAGADI,ROHAN   MAGDUM","D2DKOLKOL4257":"Karansinh   khot,Sujal   Sangar","D2DKOLKOL4165":"Sachin  madhukar patil,ABHISHEK  PATIL","D2DKOLKOL4132":"OMKAR AGANDA BHOPALE,Aditi  Bhopale","D2DKOLKOL3640":"VAIBHAV PRAKASH KUMBHAR,Prakash  lad"},"NA":{"D2DKOLKOL3091":"Bhagyashree  Amol Mulik,Amol  Ram Mulik"}}},"PARBHANI":{"MMU Camp":{"TUSHAR  TONGALE":{"MMU0006461":"VAISHNAVI PARAJI ASHTAKAR,VASUDHA GULABRAO BHOSLE"}},"DOOR TO DOOR":{"ANJALI DHURAJI ZODPE":{"D2DPARPAR6785":"AMMAR AHMED ABDUL MAJEED,SHAIKH  KHADIR","D2DPARPAR6333":"SAMREEN SHAIKH KHAJA,SALMAN RAFIK SHAIKH","D2DPARPAR5704":"KHIJAR JILANI SHAIKH,YOGESH PANDURANG PAWAR","D2DPARPAR4985":"AKASH  BHALERAO,KAMEL  HABIB KHAN","D2DPARPAR4318":"SHAIKH ABDUL HAQUE  ATEEQUE,MAHEEN  KHAN","D2DPARPAR4310":"RUSHIKESH  PANDURAN GAAVAK,SANTOSH  RAUT"},"Mois Khan MujaffarKhan Pathan":{"D2DPARPAR6717":"ATUL  SAWANT,SOMESHWAR NAMDEV SATHE","D2DPARPAR6670":"AKASH BALASAHEB KHATING,SITARAM   KAMBLE","D2DPARPAR6330":"SUDARSHAN  RANKHAMBE,PRASAD   WALKE","D2DPARPAR6175":"SUGRIV   SARUKE,SANDIP RAJEBHAU CHAVAN"},"ROHIT VIJAYANAND WAGHMARE":{"D2DPARPAR6706":"SHAIKH AKRAM SHAIKH KHAJA,SYED AYFAZ RAZVI SYED ANSAR RAZVI","D2DPARPAR6705":"SOPNIL GANESH SONWANE,SAURABH PRABHAKAR DHAGE","D2DPARPAR6704":"PRATIK   SALVE,VAIBHAV SHESHRAO GAVANDE","D2DPARPAR6671":"CHANDRAKANT SHANKARRAO MARALE,SATYAM SANJAY AMBORE","D2DPARPAR5976":"IRFAN   KHURESHI,VINAYAK MAROTRAO SHINDE","D2DPARPAR5179":"SANDIP  BALASAHEB KANKUTE,SWAPNIL   KANKUTE"},"PRADIP  VASANTRAO MATE":{"D2DPARPAR6669":"Sumit  Sanap,PARMESHWAR   PAWAR","D2DPARPAR6652":"PRASHANT GANESHRAO KHILLARE,Harish Dattarao Palve","D2DPARPAR6624":"YOGESH YASHWANT SONULE,AKSHAY   JADHAV","D2DPARPAR6260":"PATHAN SHOEB SALIM KHAN,SHEKH AWAIZ SHAIKH ISMAIL"},"VIJAY BALASAHEB DESHMUKH":{"D2DPARPAR6561":"SHAIKH JUNAID SHAIKH GAFFAR,Shaikh Fahim Shaikh Musa","D2DPARPAR6120":"LAHUJI  KACHARUBA MATHNE,TAUHEED MUJEEB KHAN","D2DPARPAR5768":"ANIKET   KAMBLE,KHAN HUJEFKHAN SHABBIRKHAN","D2DPARPAR4698":"MANOJ ATMARAM KAMBLE,KULDEEP  VITTHALRAO LANDGE","D2DPARPAR3385":"AJAY  YENGADE,MUNJA  VIRKAR"},"Rahul  Shivajirao Dudhare":{"D2DPARPAR4907":"ANSARI MOHAMMAD MUJAHED ABDUL SAGEER,SHAIKH  SIRAJ SHAMSHU","D2DPARPAR4744":"ABDUL   Wase,MOHAMMED ALI KHAN ASLAM  KHAN","D2DPARPAR4374":"Abdul Mobeen  Kaleem,NAVEED   KHAN","D2DPARPAR4212":"DATTAGURU GANGADHAR HIVARE,ZIYAUR  JILANI","D2DPARPAR4010":"NILESH SHIVAJI BANMARE,SARTHAK  KAMBLE","D2DPARPAR3697":"ABDUL QAYYUM   ANSARI,SABER  SHAIKH","D2DPARPAR3506":"SYED KALEEM  SYED SADEK,SHAIKH  JUNED ATWWQUE","D2DPARPAR1424":"KIRAN DILIP ASOLE,DILIP DIGAMBAR ASOLE"}}},"AHMADNAGAR":{"MMU Camp":{"Savita  Amar Adhav":{"MMU0006416":"Vaishnavi Sanjay Randhir,Prajakta Akshay Wairagar","MMU0003764":"Suvarna Markas Rananaware,KUSUM ISHWAR TRIBHUWAN"}},"DOOR TO DOOR":{"Puja Sudam Walve":{"D2DAHMAHM5761":"MRUGNAMAY  BHAUSAHEB SHINDE,Puja  Gorakhnath Sake","D2DAHMAHM5397":"YOGIRAJ  BHIMRAJ KARALE,Sujay Arun Netke","D2DAHMAHM4454":"Vishal Navnath Sonawane,SHUBHAM ANIL BHOT","D2DAHMAHI6740":"Pratik Satish Tapkire,Zine Rutuja Govardhan","D2DAHMAHI6686":"Karan  Anil Kudiya,Rushikesh Magan Bavche","D2DAHMAHI6634":"NIVRUTTI SHANKAR PAWAR,Umesh  Maroti Dhabale","D2DAHMAHI6047":"Shivam  Dattatray Suravase,Sandip Sanjay Pawar","D2DAHMAHI5957":"Ganesh  Kashinath Dalavi,Rohit  Sadashiv Chavan","D2DAHMAHI5942":"Avinash Nandu Korekar,Arjun Arun Chavhan"},"GOVIND BABASAHEB NARSALE":{"D2DAHMAHM5700":"Pankaj  Dattatray Vitnor,Arjun  Dattatraya Vitnor","D2DAHMAHM5534":"Nikita Abhay Teltumbade,Bhushan Babasaheb Raut","D2DAHMAHM5423":"Prashant Tatyasaheb Tarhal,Akash Somnath Somvanshi","D2DAHMAHM4795":"Akash Vishnu Raut,Saurabh Rajendra Ingale","D2DAHMAHM4514":"SUJIT  SANJAY PAWAR,Ajit Sanjay Pawar","D2DAHMAHM4460":"Mahesh  Ramdas Donde,Prashant Dnyandev Dahadonde","D2DAHMAHM4334":"Krushna Namdev Waydande,Tejas Babasaheb Rode","D2DAHMAHM4333":"Mayur Ramdas Patare,Vaibhav Ashok Gavhane","D2DAHMAHM3143":"GANESH RAMESH NIKALJE,DNYANESHWAR RAMESH BHAGWAT","D2DAHMAHI6244":"Yogesh Bhausaheb Nangare,Raj Dattatray Adsure","D2DAHMAHI6208":"Popat  Ashok Vitnor,Sitaram Shahadev Gardhe"},"Priti Sachin Shete":{"D2DAHMAHM5600":"Sanket Vilas Jangale,Sachin Raju Madane","D2DAHMAHM4947":"Rahul  Navnath Dahifale,Devidas Balasaheb Dahifale","D2DAHMAHM3125":"SUNIL ANIL SHERE,LAXMAN RAVSAHEB KAMBALE","D2DAHMAHI6224":"Akshay Rajendra Ware,Shatrughn Chandrakant Sawase","D2DAHMAHI6223":"Yogesh Rangnath Khomne,Krushna Tukaram Solat","D2DAHMAHI6218":"Ganesh Suresh Giri,Ashok Rangnath Jadhav"},"Komal Prakash Pathade":{"D2DAHMAHM5282":"Dattu Kishor Thorat,Ganesh Dhuleshwar Thorat","D2DAHMAHM4650":"Ajay  Sanjay Gaikwad,Vijay Babasaheb Bhosale","D2DAHMAHM4077":"MANISHA  NANDU BOMBALE,Rajendra  Machhindra Chindhe","D2DAHMAHI6760":"Mohini  Amol Bhokare,MAYURI BHAUSAHEB AHIRE","D2DAHMAHI6720":"Pooja  Babasaheb Bhosale,KRISHNA VISHWANATH GADEKAR","D2DAHMAHI6582":"Pratik Vijay Kobarne,Pooja Daadasaheb Ghorpade","D2DAHMAHI6321":"Rutika  Sharad More,Lalita  Ashok Bhalerao"},"Shivkanya Dattatray Mehetre":{"D2DAHMAHM5039":"Vaibhav  Punjaji Kharat,Abhishek Sunil Kadam","D2DAHMAHM5038":"Sanket  Arun Narode,Prasad Nandkumar Kape","D2DAHMAHM4759":"Rushikesh Balasaheb Vahadane,Saurabh Prakash Kothale","D2DAHMAHI6698":"Suraj  Sunil More,Akash Sunil Dawane","D2DAHMAHI6552":"Tejas Balu Karale,Sumit Umesh Rathod","D2DAHMAHI6305":"Bhushan  Bharat Sonawane,Tushar Sandip Ghandat"},"AADESH  RADHAKISAN PAWAR":{"D2DAHMAHM4725":"Yogesh Satish Barge,Subodh Bhaskar Tambde","D2DAHMAHM2621":"TEJAS VIJAY SHENDGE,PRATIK MAHADEO KAKADE","D2DAHMAHI6667":"Laxman  Namdeo Shelke,VRUSHABH SANTOSH BHANDARI","D2DAHMAHI6666":"Siddhi  Somnath Pandit,Sakshi Bharat Dahane","D2DAHMAHI6665":"Shubham Ashok Bhise,RAKESH  RAJENDRA MATE","D2DAHMAHI6659":"Sandeep  Dilip Palve,Yogiraj Laxman Arvel","D2DAHMAHI6530":"Dhiraj Balasaheb Rajguru,Punam Mahesh Korde","D2DAHMAHI6476":"Aadesh Satish Barge,Vikram Ananda Gavhane","D2DAHMAHI6271":"Anil   Navnath Wagh,Ashwini  Suraj Shinde"},"Sagar Babasaheb Bhosale":{"D2DAHMAHM3810":"Harshal Ramnath Kachare,Bhagyashree Pandurang Gabhale","D2DAHMAHM2240":"ARVIND  GANESH PAWASE,SACHIN AMBADAS MEDHE","D2DAHMAHI6310":"Sachin  Sanjay Kharat,Aniket Sanjay Kharat","D2DAHMAHI6264":"Prashant  Sudhakar Pawar,Avdhut  Sanjay Walunj","D2DAHMAHI6253":"Yogesh Vitthal Pokale,Aditya Annasaheb Gunjal","D2DAHMAHI6245":"Mahesh  Ramesh Rajguru,Vishal Nandu Ghotekar","D2DAHMAHI6034":"Divya Sanjay Pawar,Amit Arun Narode"}}},"PUNE":{"MMU Camp":{"Abhishek Rambhaji Lokhande":{"MMU0006400":"VAISHNAVI SHRIKANT ADKAR,PRASHANT BHARAT ZAWARE"}},"DOOR TO DOOR":{"ROHAN MINANATH WAKCHAURE":{"D2DPUNBAV6767":"SAHIL RAJU SAWANT,Reshma  Vijay pradhan","D2DPUNBAV6718":"SHANKAR   JADHAV,MANOHAR BHARAT MANE","D2DPUNBAV6312":"ASHWINI   HANDE,YOGESH RAMDAS HANDE","D2DPUNBAV6311":"SNEHAL   KURHADE,NIKHIL CHANDRAKANT KURHADE","D2DPUNBAV5810":"Vijay Dhanaji Pawar,Pratik Vijay Pawar","D2DPUNBAV4987":"DATTATRAY ANKUSH PAKHARE,POOJA   JADHAV","D2DPUNBAV3663":"SUMIT  ALHAT,POONAM  AMBRE","D2DPUNBAV2722":"Pravin  Walunj,Pratik   karale"},"SACHIN RAMESH ZAREKAR":{"D2DPUNBAV6728":"PRADIP  PANDURANG MISAL,MAHESH  CHAUDHARI","D2DPUNBAV6550":"MAHADEO  MARUTI KATURE,VICKY  SUNIL CHAVAN","D2DPUNBAV6549":"ASHITOSH   KHANDEKAR,AMOL JALINDER DHAYGUDE","D2DPUNBAV6548":"NILESH  BATKHAVAR,ONKAR   TAKAWANE","D2DPUNBAV6547":"Rohan Deepak Shinde,UDAY   WAKHURE","D2DPUNBAV6544":"TUSHAR   BADHE,VINAYAK   LONDHE","D2DPUNBAV6543":"AKASH   HARE,SHAILA  KISAN JADHAV","D2DPUNBAV6542":"SHIBSANKAR   DAS,Kaveri  Nikhil Gawade","D2DPUNBAV6541":"ROHINI  PRASHANT KAMBLE,SAKSHI  SUDHAKR BHILARE"},"Jagruti Sanajy Ingale":{"D2DPUNBAV6563":"Vaishnavi  Pore,AJAY   YADAV","D2DPUNBAV6525":"Dhanshree   Deshmukh,NAVNATH   LANDE","D2DPUNBAV6524":"RIYAJ  PATEL,SATISH   LANDE","D2DPUNBAV6523":"VIDYA PRADIP BHOSALE,SWATI GANESH NAVGHARE","D2DPUNBAV6314":"VEDANT JAGDISHSINGH PAWAR,Nirmal Vitthal More","D2DPUNBAV6313":"SHUBHAM SANJAYSINGH PAWAR,ADESH ANIL NARWADE","D2DPUNBAV5931":"Sudarshan Vilas Kurkute,ADITI   KHAMKAR","D2DPUNBAV5896":"SADAF   SHAIKH,MOIN TANVEER SHAIKH","D2DPUNBAV3052":"PRITESH  MADHAV BHUTE,PALLAVI  PRAVIN BHANDARKAR"}}},"GONDIA":{"MMU Camp":{"Akash Sharwanji Hatwar":{"MMU0006376":"Shrawani  Narendra Bahekar,Laxmi  Bhagvat Nagpure","MMU0003536":"Sanghmitra  Meghnath Ganvir,Pragati  Vishal Gajbhiye"}},"DOOR TO DOOR":{"AKASH  DEVANAND DHEKWAR":{"D2DGONGON6759":"Khushal Chhatrapal Bopche,Sachin Pralhad Lilhare","D2DGONGON6590":"AKSHAY BAIJNATH RAHANGDALE,SANDIP  NHOJRAJ KOTANGLE","D2DGONGON6345":"Chhatrapal Dumendranath Rahangdale,Devishankar  Sitaram Gautam","D2DGONGON4764":"Jayashri  Hivraj Khune,Mohini  Omprakash Nakade"},"Pakesh  Tekraj Bisen":{"D2DGONGON6229":"Himali Markand Rahangdale,Swati Bhumeshwar Baghele","D2DGONGON4693":"Nitesh  Dulichand Dasariya,Krsankant Shrawan Damahe","D2DGONGON2861":"KHUSHALDAS  HIRADAS LILHAR,PRAVINKUMAR BHERSINGH BANOTHE","D2DGONGON2485":"RANJANA  RAVI FARKUNDE,PRITI  RAVIKUMAR UPWANSHI"}}},"CHHATRAPATI SAMBHAJINAGAR":{"MMU Camp":{"Satish Namdev Kale":{"MMU0006370":"Pallavi Vilas Mokase,Reshma Haribhau Wagh"},"SATISH RAMESH GAIKWAD":{"MMU0003555":"DIKSHA  BHAGWAN SHARNAGAT,SAVITA  DNYANESHWAR CHAVAN"}},"DOOR TO DOOR":{"PATHAN UZAIF  ZAFAR KHAN":{"D2DCHHKAN4098":"NILESH NANDU JADHAV,EBAD  SHAIKH","D2DCHHKAN2761":"LAXMAN  KARBHARI GHUGE,GAURAV SITARAM GHUGE","D2DCHHCHH6722":"ZAKIYA   MOSIN,AYAN ASIF SHAIKH","D2DCHHCHH6354":"PATHAN ZAMEER KHAN RAUF KHAN,SHAHEBAZ SALIM QURAISHI","D2DCHHCHH5991":"ARBAAZ   PATHAN,SAGAR ISHWAR MORE","D2DCHHCHH5789":"KUNAL NAMDEV DAWANGE,MAYUR PANDURANG MOKASE","D2DAURKAN2404":"NITIN SANJAY DAWANGE,SAMADHAN RAMU NAWALE"},"SHOEB BABUMIYA DESHMUKH":{"D2DCHHCHH6784":"asef  aslam shaikh,PATHAN SHAHID KHAN SHAKEEL KHAN","D2DCHHCHH6556":"NIKHIL SANTOSH SHELKE,Akash Sidharth Kakade","D2DCHHCHH6441":"YUVRAJ   WAGH,JAYASHRI VISHVANATH DONGRE","D2DCHHCHH5973":"ALTAMASH MANSUR SHAIKH,SHAIKH SARFRAZ SADIQUE","D2DCHHCHH5738":"KIRAN SANDEEP MEHTRE,USHABAI JAYESH PAREDESHI","D2DCHHCHH4057":"SHAIKH  AHATESHAM AMINODDIN,AMINODDIN  SHAIKH","D2DCHHAUR3583":"PAWAN RAMESH MEHRA,AKASH RAMESH MEHARA"},"AJIT  DATTATRAY LOKHANDE":{"D2DCHHCHH6765":"CHETAN  BADRINATH ANDHALE,GANESH VITTHAL JAGATAP","D2DCHHCHH6217":"MANGESH RAMESH PALODE,Ajay Krushna Sapkal","D2DCHHCHH6110":"Mahesh Ravsaheb Thorat,Shrihari Ranganath Shirsath","D2DCHHCHH5759":"PRAJAKTA RAMESH MUNDADA,AJINKYA SANTOSH RAUT","D2DCHHCHH5758":"Sagar kashinath Palaskar,Pavan Shravan Erande","D2DCHHCHH5596":"VISHAL   NACHAN,VAISHNAVI   SONWANE","D2DCHHCHH4930":"KRUSHNA  DEVIDAS DARADE,VAISHNAVI  RANGNATH TAYDE","D2DCHHCHH4567":"KISHOR  CHAVAN,VAIBHAV  APPASAHEB AGVANE","D2DCHHCHH4471":"GANESH DADARAO DANDGE,GANESH  SAPKAL","D2DCHHAUR3415":"Rahul  Thorat,Shrddha  Thorat"},"Vikki Rameshwar Ranmale":{"D2DCHHCHH6683":"KIRITIKANT   MHASKE,VAIBHAV APPASAHEB PATOLE","D2DCHHCHH6572":"RUPALI RAJU NAIKWADE,CHAITNYA  SHELKE","D2DCHHCHH6045":"PAVAN KAKASAHEB DERE,BALIRAM VISHWANATH CHATE","D2DCHHCHH4603":"RUSHIKESH   PATIL,YOGIRAJ  KACHARE","D2DCHHCHH4104":"VAIBHAV SANJAY SOSE,AMOL SHIVAJI SOSE","D2DCHHCHH3948":"AMRUTA  RAJENDRA RODI,NITIN  MATHARKAR","D2DCHHAUR3439":"VISHVAJIT BHAGVANSING MORE,ARJUN  CHAVAN"},"Rameshwar  Damu Umbarkar":{"D2DCHHCHH6653":"PANKAJ PRABHAKAR ANDHALE,SACHIN NANA SONWANE","D2DCHHCHH6327":"GAJANAN APPARAO RAUT,Anjan Asaram Devkar","D2DCHHCHH5986":"KAVITA   JADHAV,SWAPNALI   MALODE","D2DCHHCHH5742":"ARTI  KOLTE,Vijay   Sapkal","D2DCHHCHH4189":"RAVINDRA  RAMBHAU SHINDE,RAGHUNATH RAJARAM GHEMBAD","D2DCHHAUR2713":"VISHAL ASHOK JADHAV,ROHIT JANARDHAN DANGODE","D2DAURAUR790":"Swapnil yashwant hiwrale,siddhant  dilip hiwrale"},"VISHAL SURESHRAO PRADHAN":{"D2DCHHCHH6453":"BHAGWAN ASHOK BANKAR,RUSHIKESH WALMIK BAGUL","D2DCHHCHH6037":"Datta   kangane,KARAN SUPADU BASANTE","D2DCHHCHH5996":"Krushana Dattarao Sirame,Shubham Dattarao Sirame","D2DCHHCHH5682":"HARSHWARDHAN   MANURE,PATHAN  FARID SAYEED"},"Krushna Ramrao Sapkal":{"D2DCHHCHH4474":"Akshay  Susundre,shubham   Susundre"}}},"RATNAGIRI":{"MMU Camp":{"PIYUSH SURESH UPADHYE":{"MMU0006233":"Sejal Chandrakant More,Saloni Sagar Shinde"}},"DOOR TO DOOR":{"Gargi Sanjay Vilankar":{"D2DRATRAT6580":"Shreyas Suresh Mestri,Vivek Vijay Mestri","D2DRATRAT6519":"Payal Vinayak Khervaskar,Mrunal Mahesh Khedekar","D2DRATRAT6518":"Deval Pravin More,Devsmi Deval More","D2DRATRAT6374":"Bhakti Gangadhar Thik,Gauresh Jayprakash Dhavade"},"Prathamesh  Balkrishna Mestri":{"D2DRATRAT6579":"Sonali Sanjay Jabare,Shweta Santosh Dhangade","D2DRATRAT6482":"Abhishek Harishchandra Padir,Karan Mahendra Golambade","D2DRATRAT6203":"Komal Ramchandra Patil,Prasad Ganesh Kamtekar","D2DRATRAT6064":"Runali Rohit Gawade,Simali Chandrakant Kamble","D2DRATRAT5967":"Vishweshwari Parshuram Khedekar,Jitendra  Surendra Darekar","D2DRATRAT5402":"Manoj Roshanlal Jain,Tina Manoj Jain"},"Saloni Vilas Shetye":{"D2DRATRAT6515":"Naziya Nazir Murudkar,Komal Sumit Kangale","D2DRATRAT6412":"Pankaj  Gangadhar Sansare,Meenakshi  Gopal Moolya"}}},"NAGPUR":{"MMU Camp":{"Sagar Gopalrao Kherde":{"MMU0006103":"Prachi  Sanjay Dodmise,Vidya Gajanan Gajabe","MMU0006082":"MANISHA MANGESH SAWLE,PRAGATI  GAJANAN GIRADKAR"}},"DOOR TO DOOR":{"Priyali  Vinod Tale":{"D2DNAGRAM6057":"SWEETY GANESH PACHGHARE,Pawan Ashok Sarode","D2DNAGNAG5231":"Prashant  Vijay Umalkar,Sneheel  Rambhau Wakekar","D2DNAGNAG5099":"Amit Kalipado Pande,Arup  Kalipado Pandey","D2DNAGNAG5074":"Shaikh   Jabbar Sadiq,Aafreenbee  Shaikh Sadiq","D2DNAGNAG4159":"Vishal   Raju Rahulkar,Tashu Kishor Bagde","D2DNAGNAG3943":"SAMIKSHA DHANRAJ DESHMUKH,Kavita   Ashok Donekar","D2DNAGNAG2533":"MAYUR  VIJAY MOHANE,SAKSHI  VINOD BORKAR","D2DNAGNAG1281":"Rupali   Tambe,Ashwin Premchand Nitnaware"},"Nikita  Himmat Kapgate":{"D2DNAGNAG6761":"Anjali  Arjun Shahu,Gaurao  Shivprasad Dhamade","D2DNAGNAG6480":"Ravina Bouddhaprakash Nagdetoe,Mrunal  Shamkarn Lokhande","D2DNAGNAG6212":"Mayuri  Sanjay Wadichar,Anju  Rajkishor Ram","D2DNAGNAG6098":"Kavita  Amol Lodhi,Amol  Ramlal Lodhi","D2DNAGNAG5577":"Monali  Dhanraj Ghodmare,Ishika  Narendra Fadtare","D2DNAGNAG5184":"Sakshi Dipak Godbole,Priyanka  Dinesh Bisen","D2DNAGNAG4332":"Prachi Shiwakar Sonawane,RITIK  NATTHUJI GAWAD"},"Khushi  Manohar Ramteke":{"D2DNAGNAG6699":"Arvind   Ramdas Chouhan,Ruchita  Rajesh Lilhare","D2DNAGNAG6479":"Sangita   Dhargave,Dilip  Namdev Dhargave","D2DNAGNAG6413":"AKANSHA  VIJAY KOCHE,Pradnya  Anurag Tilwar","D2DNAGNAG6255":"Anshul Ramji Pahune,Gaurav  Dharmraj Gharjale","D2DNAGNAG6029":"Shubham  Vilas Kezarkar,Achal  Arun Mankar","D2DNAGNAG5606":"SHOEB MOHAMMADSHAFI SHAIKH,Maqbool Warsi  MohammadFarooq Ansari","D2DNAGNAG4993":"Rajesh Shantaram Yadav,Harsh Rajesh Yadav","D2DNAGNAG3163":"Mohammad Sameer AbdulMujib Ansari,Ghayas Sheikharoon Sheikh"},"SAMIKSHA PRAMOD LANDE":{"D2DNAGNAG6599":"Chirag  Dharmrao Moon,Pranshi  Prakash Bisoriya","D2DNAGNAG6007":"Shraddha  Manohar Bhalme,Snehal Jagadishrav Mendhe","D2DNAGNAG583":"Shobha Mayur Patil,Mayur  Ashok Patil","D2DNAGNAG4669":"Swati Uttamrao Kalpande,Rajat  Kishor Bahadure","D2DNAGNAG4517":"Dipak  Krishnarao Rokde,Manisha  Dipak Rokde","D2DNAGNAG2627":"MANGESH DEVRAO CHAVHAN,MEGHA MADHUKAR MUDRAKE","D2DNAGNAG1729":"Archana Dinesh Ghate,Sakshi Ravindra Ban","D2DNAGKAT5283":"Samiksha Sureshraoji Kalbande,Amit  Gangadhar Dhande"},"Vishakha Keshao Wankhede":{"D2DNAGNAG5572":"Pratiksha  Chatrapati Wagh,Ritik  Pranhans Shende","D2DNAGNAG4873":"Pawankumar  Bardani Samundre,Radhika  Chetram Samundre"}}},"HINGOLI":{"MMU Camp":{"Avinash  Bharat Bonakudkew":{"MMU0006019":"PRAMOD  JAGDEVRAO POLE,KIRAN ARVIND KAMBLE"}},"DOOR TO DOOR":{"GANESH  INGOLE":{"D2DHINHIN6663":"SANTOSH   SAKHARE,BRAMHANAND   BENGAR","D2DHINHIN6457":"DNYANESHOR GOVINDARAO BHOSLE,OMKAR SHANKAR GAWANDE","D2DHINHIN6280":"Pramod Rameshwar Lothe,ANKUSH BABURAO JADHAV","D2DHINHIN5053":"AMOL HARINATH DHAYDE,BHAGWAT   PAWAR","D2DHINHIN4576":"SUDERSHAN   GHUGE,YOGESH   GHUGE","D2DHINHIN4376":"PRADIP  THITE,DATTA  SARKATE","D2DHINHIN1322":"SAMIR  LALLU PYAREWALE,SAYYED AMJAD NASEER"},"Uttam Ukandi Sarkate":{"D2DHINHIN6567":"SUNNY SANJAY KHANDARE,MAYUR MADHUKAR MULE","D2DHINHIN6380":"AKSHAY VILAS KHANDARE,SACHIN ASHOK KAMBLE","D2DHINHIN6338":"AJAY DILIP RATHOD,KARTIK   CHAVAN","D2DHINHIN5911":"SIDDHARTH  KAILAS INGOLE,Aabasaheb Narayanrao Solanke","D2DHINHIN5108":"GANESH BHAGWANRAO SHINDE,SUDARASHAN   KARHALE","D2DHINHIN4575":"GANESH   LAD,RAJSHEKHAR   WATHORE","D2DHINHIN4553":"BALASAHEB   SHINDE,GAJANAN BAPURAO SHINDE"},"GOPAL PANJABRAO KUTE":{"D2DHINHIN6391":"AKSHAY SARANGDHAR DESHMUKH,Pavan Narayan Gadade","D2DHINHIN6378":"GOPAL   ZADE,AVINASH DEVIDAS SHINDE","D2DHINHIN6377":"AKARSHAN  KUNDLIK JADHAV,AKASH BANSHI PAWAR","D2DHINHIN5699":"NIKHIL MAROTI ATHAWALE,TUSHAR SHIVAJI SHINDE","D2DHINHIN4531":"DHANANJAY  RAJESH TALE,OM BHAGAVAT TALE","D2DHINHIN4421":"GOVIND   HARAL,KARAN  RATHOD","D2DHINHIN4420":"YOGESH SHANKAR HARALE,MAHADEV BHASKAR KHANDARE"},"MANOJ  SURYAWANSHI":{"D2DHINHIN5701":"VISHAL SANTOSH TARKHE,AVINASH VISHANU ATHAWALE","D2DHINHIN4763":"SHAIKH AZHAR NOOR,SHAIKH VASIM LAL","D2DHINHIN4580":"RUSHIKESH   KADAM,BALASAHEB   PADOLE","D2DHINHIN4579":"SHUBHAM   SURYAWANSHI,YOGESH  BHOSLE","D2DHINHIN4578":"RUPALI KONDIBA SAVANDAKAR,ROHIT   KHANDARE","D2DHINHIN4370":"GOVIND SHANKARBUVA BHARTI,GAUS KHAN WAHEED KHAN","D2DHINHIN4359":"ARTI BABURAO KAMBALE,SWARUP PRATAP NARWADE"}}},"BEED":{"MMU Camp":{"PIYUSH SURESH UPADHYE":{"MMU0005849":"SAKSHI   MAHAKUNDE,GITA   SHERKAR"}},"DOOR TO DOOR":{"ROHIT RAMESH KANADE":{"D2DBEEBEE6727":"Parwez  Mastan Shaikh,SUSHANT  RANJIT JADHAV","D2DBEEBEE6664":"SHIVRAJ  KISHAN GITTE,BALAJI NAGNATH MUNDE","D2DBEEBEE5907":"AJAY  JADHAV,SAURABH  RATHOD","D2DBEEBEE4134":"SHARAD  DILIP PATIL,VAIBHAV  SHIVAJI PAWAR","D2DBEEBEE3325":"MOHAMMAD ARSHAD  ASHRAF,SHAIKH MOHAMMAD  ABED"},"SAURABH  SUNIL DHOLE":{"D2DBEEBEE6712":"BHAGAVAT  VISHNU GHULE,NIKHIL  BANDU KOLHE","D2DBEEBEE6711":"ROHAN  UTTAM NIKALAJE,GANESH  RADHAKISAN BEDKE","D2DBEEBEE6707":"ADARSH  BALU GHADGE,NIKHIL  KOTHEKAR","D2DBEEBEE6655":"PRATHMESH  LAHANE,NITIN   THOKE","D2DBEEBEE6446":"KARAN  ASARAM SHINDE,AJAY BHAUSAHEB NAKADE","D2DBEEBEE5104":"SARTHAK  GHORAD,MAHESH  KAILASRAO SHEJAL","D2DBEEBEE4607":"Mohammad   faheemoddin,SACHIN    JADHAV","D2DBEEBEE2616":"FAISAL KHAN  SIRAJKHAN PATHAN,SHAHEBAZ  WAHID KHAN","D2DBEEBEE2044":"PATHAN  ATIKRASHID KHAN,ZAKI  SHAIKH","D2DBEEBEE1230":"SAWAPNIL  VIJAY SALVE,CHATE  BAPURAO"},"VIKAS GULAB JADHAV":{"D2DBEEBEE6658":"Altaf  Mukhid Shaikh,UMESH GANGADHAR NAGARGOJE","D2DBEEBEE6636":"GANESH NAVNATH JADHAV,SHUBHAM BAJRANG RAUT","D2DBEEBEE6420":"UMARKHAN  AYYUBKHN PATHAN,KURESHI  SAIFYODDIN RAJIYODDIN","D2DBEEBEE6390":"AKASH ABHIMAN NAGARGOJE,RAHUL DHANRAJ TONDE","D2DBEEBEE6386":"ROHIT   AVAD,RITESH NAVNATH RATHOD","D2DBEEBEE5939":"AKASH  NAGURAO RATHOD,SUMIT GULAB RATHOD","D2DBEEBEE5818":"VIVEK  AASARAM BADE,VIJAY   GILBILE","D2DBEEBEE4684":"ABHISHEK  SANTRAM THITE,Ajinkya Shrikisan Raut"},"Kishor Popat Shelke":{"D2DBEEBEE6654":"ALOK   AGLAWE,SANJAY BIBHISHAN MUNDE"}}},"JALGAON":{"MMU Camp":{"Yogesh Ramesh Gadhe":{"MMU0005808":"Soni Chitraram Khokar,Kanchan Rahul Gayakwad","MMU0005132":"Vivek Balawant Bhalerao,Mayur Dnyaneshwar Patil"}},"DOOR TO DOOR":{"Nayana Sandeep Thakur":{"D2DJALMUK6371":"Aslam Shah Afzal Shah,Shaikh javed Ahemad Abdul Hamid","D2DJALMUK6232":"Shivam Rajendra Tayade,Aaryan Pramod Ingale","D2DJALMUK5940":"Rajesh Ganesh Chavhan,Chaitali Khushal Sontakke","D2DJALMUK4756":"Shaikh  Danish Naeem,Mustaquim  Habib Nazim","D2DJALMUK4427":"PANKAJ  KAILAS THAKNE,CHETAN  ARUN LAHASE","D2DJALMUK3681":"Gajanan Vishwanath Masane,Vaibhav Dilip Lahase","D2DJALMUK2819":"KAMALESH SUNIL DHUNDLE,VIKAS KAILAS SABALE","D2DJALMUK205":"Amol  Damodhar Singh,Vaibhav  Rajendra Gadhe"},"AVINASH RAJU BARI":{"D2DJALJAL6777":"Manoj Vikram Rathod,Sagar Bhalchandra Patil","D2DJALJAL5711":"Mamta Krushna Dapse,Divyani Sanjay Sushir","D2DJALJAL5708":"Sandip Tukaram Jadhav,Pavan Ishwar Pavar","D2DJALJAL4529":"Feroz Ahmed Shaikh Rahmtulla,Amit Pralhad Wani","D2DJALJAL3843":"Sagar Ramdas Naik,Prasanna Sunil Sonawane","D2DJALBHA6755":"Sachin  Ramesh Pawar,Vishal Sanjay Dhakare","D2DJALBHA6196":"Tofik Gani Shaikh,Nilesh Hiraman Mahajan","D2DJALBHA3933":"Yogita Vijay Chavhan,Bhavesh Anil Rajput"},"Karansing Ramdas Patil":{"D2DJALJAL6583":"Shaikh Aasif Ameenuddin Mujawar,Irfan Ahamad Shakil Qureshi","D2DJALJAL5923":"Hitendra Sanjay Mahajan,Shashikant Vasant Mahajan","D2DJALJAL5894":"Shaikh Rehan Ahmed Shakiloddin Mullaji,Rizwan Ahemad Kamaloddin","D2DJALJAL5816":"Motilal Namdev Patil,Hrishikesh Kantilal Shimpi","D2DJALJAL5792":"Dipak Rajendra Mahajan,Nilesh Bhoju Chavan","D2DJALJAL5783":"Milind Kishor Pawar,Chndrakant Vasant Mahajan","D2DJALJAL5747":"SHAHID AKHTAR NIZAMODDIN  MULLAJI,AKHLAK AHMAD ZAHIRODDIN  MULLAJI"},"LOKESH SHRIKANT PATKARI":{"D2DJALJAL6226":"SAGAR RAMESH SANAP,Rajeshree Satish Wagh","D2DJALJAL5893":"SAMIR SAGIR SHAIKH,Vishwajit Balawant Bhalerao","D2DJALJAL4829":"Pravin  Indal Rathod,Kalpesh  Dnyaneshwar Patil","D2DJALJAL4778":"Shekhar Bansilal Sapkale,SUNIL BABAN ANAPAT","D2DJALJAL4297":"Mahesh Balu Patil,Dipak  Madhukar Pawar","D2DJALJAL3608":"Tamboli  Jaid Shaikhroshan,SHAIKH NADEEM SHAIKH  IBRAHIM","D2DJALJAL3174":"YASH GAUTAM JANJALE,RAHUL NITIN SAPKAL","D2DJALBHA6738":"Swati  Nitin Bagade,Pruthviraj Vasant Pawar","D2DJALBHA4105":"SAMADHAN DNYANESHWAR MALI,RAJENDRA DHARMA MALI","D2DJALBHA4021":"AMOL  ABHIMAN BHALERAO,Pratik  Kiran Jadhav","D2DJALBHA3373":"GAURAV SHYAM PATIL,BHUSHAN SUDHAKAR MAHAJAN"},"PUNAM ASHOK RAYSING":{"D2DJALCHO5800":"Sunil Shriram Saindane,Jitendra Suresh Koli","D2DJALCHO5757":"Kunal Suresh Chavhan,Komal Nandu Pardhi","D2DJALCHO5601":"Amol Shivdas Koli,Nitin Rohidas Kapdane","D2DJALCHO4784":"Gaurav  Bharat Shirsath,Jitendra Vitthal Mahajan","D2DJALCHO4783":"Prashant Vinod Chaudhari,Dattatray Dnyaneshwar Mahajan","D2DJALCHO4487":"Rohan Narendrasin Janakwar,Gaurav Anil Chaudhari","D2DJALCHO4307":"Ganesh Pralhad Salunkhe,Vishvas Bharat Sonawane","D2DJALCHO3985":"NILESH RAMDAS MALI,AVINASH  SHIVDAS MAHAJAN"}}},"MUMBAI CITY":{"MMU Camp":{"GOURAV  NARESH MHATRE":{"MMU0005556":"Ruksar Abdul Hai Khan,Mohammed Tauqeer Irfan Mujawar"},"Dilip Kumar Jaiswar":{"MMU0004361":"Suman Ramshiromani Saroj,AFRIN  HAMIDULLAH KHAN"}}},"AMRAVATI":{"MMU Camp":{"KUNAL MANOHAR SONPAROTE":{"MMU0005471":"SUMIT  NANDKISHOR GOLAIT,GAURI   KANDALKAR"}},"DOOR TO DOOR":{"PRIYANKA VISHNUJI NIMKAR":{"D2DAMRAMR6775":"SANJANA DILIP KHANDARE,RANI MANOJ MESHRAM","D2DAMRAMR6702":"ROSHAN GAJANANRAO PATIL,NILESH  TRAMBAK RAUT","D2DAMRAMR4801":"SUMIT  VINAYKRAO VIRULKAR,MINAL   DOKE","D2DAMRAMR4731":"NITESH  ASHOKRAO DAHAKE,ABHINAV RAJENDRA DAWANGE","D2DAMRAMR4391":"SAGAR  AWDHUTRAO JAMBHULKAR,LAXMI   JAMBHULKAR","D2DAMRAMR4389":"HARSHAL  BHATKULKAR,MAYAWATI  KAWALE","D2DAMRAMR4386":"NITIN  HIVE,ANKUSH BALASAHEB MUNDANE","D2DAMRAMR4383":"SHIVRAJ   WAGHADE,RUPALI   WAGHADE","D2DAMRAMR4380":"Jaya  shalikram Dhande,SUMEET  YASHWANT CHIMOTE","D2DAMRAMR3526":"KAVITA  PRAKASH CHAUTPAGAR,VIYOG  CHAUTPAGAR","D2DAMRAMR3059":"NANDINI  SATISH BHATKAR,POOJA  PADIP TAYADE"},"MAYURI ATISH RAUT":{"D2DAMRAMR6710":"LALITA GULAB PATANKAR,VAIBHAV SANJAY BOHARAPI","D2DAMRAMR6709":"ATISH  MADHUKARRAO RAUT,ASHWINI BABARAO SONARE","D2DAMRAMR6532":"KANCHAN ASHOK GHORPADE,SONU VINODRAO WANKHADE","D2DAMRAMR6456":"VAIBHAV   RAUT,DEEPESH PRAKASH GAJBHIYE","D2DAMRAMR6284":"ADITYA RAJENDRA TAYADE,KARTIK   CHAVHAN","D2DAMRAMR5618":"SANKET   RAWALE,ANKUSH   GADEKAR","D2DAMRAMR5435":"SAYED SAQUIB ALI,DANISH  SADIQUE","D2DAMRAMR5225":"MUDASSIRS MOHD SHAH,ADNAAN  AHMAD MOBIN","D2DAMRAMR5222":"BUDDHABHUSHAN  ARUNRAO INGLE,DIPANKAR  GAUTAMRAO SHIRSAT","D2DAMRAMR4800":"SNEHA  NEWARE,AHTESHAMUDDIN  KAZI","D2DAMRAMR4781":"TEJILAL BABNU JAMUNKAR,LALITA  TEJILAL JAMUNKAR","D2DAMRAMR3869":"SONIYA SUNIL GAJBHIYE,SUNIL  GAJBHIYE"},"Manoj  Avinashe":{"D2DAMRAMR6681":"AKSHAY  ASHOKRAO DHARMALE,Gaurav Gautamrao Sirsat","D2DAMRAMR6637":"SOYAL NASIR SHAIKH,SHRUTI NANDALAL ASOLE","D2DAMRAMR6285":"MUMTAZ ALI  SATTAR ALI,GAURAV PRABHAKAR TATTE","D2DAMRAMR5640":"ANJALI  MAHENDRA NAWADE,MAHENDRA KESHWRAO NAWADE","D2DAMRAMR5223":"ROHINI  VARDHE,NARENDRA   VARDHE","D2DAMRAMR4990":"NEWTAN  CHAUTPAGAR,PRATIKSHA   GAJBHIYE","D2DAMRAMR4782":"VINOD  HANUMANT BORALKAR,LAKHAN  TARASING DEULKAR","D2DAMRAMR4780":"KIRAN ASHOKRAO NISWADE,RUPALI  NISWADE","D2DAMRAMR4769":"VIVEK  Krushna PUNSE,DHAAMMAKIRTI HARIDAS NAGDIVE","D2DAMRAMR3060":"SAMIR  SHAUKAT SHAHA,ABHAY GANESHRAO DHONDE"},"VRUSHIKA   JADHAV":{"D2DAMRAMR6349":"Tushar Dilip Rathod,NITESH  PARICHAND CHAVHAN","D2DAMRAMR6286":"SAURABH  CHAUTPAGAR,GAURAV G KARWADE","D2DAMRAMR5943":"NILESH VINAYAKRAO DHUMALE,ADESH DHARMENDRA INGALE","D2DAMRAMR5436":"RUSHABH   JADHAV,MAYUR   DONGARE","D2DAMRAMR5408":"SHITAL   LONARE,NIKITA   MESHRAM","D2DAMRAMR5227":"Anjali Ashok Bhagat,MANISHA   BHAGAT","D2DAMRAMR4798":"ANUJ  PRALHADRAO YENGALE,SANKET  DINESH SHINGNAPURE","D2DAMRAMR4382":"YOGESH  HIRAN JADHAO,SANDESH  THOOL","D2DAMRAMR4381":"NIKITA  DEEPAK JUMDE,SAURABH  SANJAY ONKAR","D2DAMRAMR1005":"LAXMI  BABARAO ARASAPURE,CHAITANYA DILIP TAYADE","D2DAMRACH96":"MOTESHIM MOHAMMAD SHAREEF,MOHAMBAD MUJAMMIL SHAREEF"}}},"DHULE":{"MMU Camp":{"BHAUSAHEB RAMESH SHELKE":{"MMU0005354":"Mayur Suresh Kachave,Shubham  Vinod Gujar","MMU0003765":"Parvej Gafoor Patel,Shubham Eknath Bhadahane"}},"DOOR TO DOOR":{"Mahendra Madhukar Jadhav":{"D2DDHUSHI6772":"Savita Gulabsing Pawara,Mohan Suresh Pawara","D2DDHUSHI6771":"Pankaj Mohan Kumbhar,Dnyaneshrwar Ashok Chavan","D2DDHUSHI6368":"Akshay Khumansing Girase,Yogesh Motiram Patil","D2DDHUSHI6159":"Arvind Narsing Pawara,BHARATI ARVIND PAWARA","D2DDHUSHI4940":"Nisha Rajendra Vasave,Pramod  Ramesh Valavi","D2DDHUSHI4476":"Jitendra Vana Pawara,Pavan Pandit Pawara"},"Shital Bansilal Sanke":{"D2DDHUSHI6770":"Rohit  Suresh Pawara,Sachin Pannalal Pawara","D2DDHUSHI6769":"Sushant Vikram Gavit,Savan Kumar Rajendra Vasave","D2DDHUSHI6768":"Rakesh Lalit Bhandari,Sunil  Mister Pawara","D2DDHUSHI6661":"Ashok  Champalal Pawara,Govind  Thavrya Pawara","D2DDHUSHI5832":"Ganesh  Namdev Pawara,Ravindra  Gabbarsing Pawara","D2DDHUSHI4569":"Bhushan  Shravan Dhangar, KUNAL SANJAY PATIL"},"Bhagwan Shankar Goykar":{"D2DDHUSAK6648":"Jayesh Bapu Malche,Gaurav   Chandrashekar Jadhav","D2DDHUSAK6647":"Prashant  Dinkar Suryawanshi,Dinesh  Rajendra More","D2DDHUSAK6529":"Wilson  Sadanand Kuwar,Vijay  Surupasing Mavli","D2DDHUSAK6191":"Yogeh  Jogilal Sarak,Digambar  Shankar Goyakar","D2DDHUSAK6184":"Esak  Dilip Valvi,Nitin  Uttam Kuwar","D2DDHUSAK3751":"Dinesh Tahanu Sarak,Prashant Nana Sarak"},"Akshay  Parashram Sawant":{"D2DDHUDHU6716":"Dipak  Kishor Wagh,Mayur Bhagwat Shermale","D2DDHUDHU6650":"Anuj Balram Chatre,Arun  Kailas Patil","D2DDHUDHU6649":"Vaibhav  Mahendra Chavhan,Umesh  Mohan Thombare","D2DDHUDHU6576":"Raj Anil Udewal,Rupesh  Mansaram Dane","D2DDHUDHU6129":"RAHUL NANA DHIVARE,Adnan  Kadir Shaikh","D2DDHUDHU5705":"ROHIT ASHOK AHIRE,Swapnil  Narendra Shah"},"Tanmay Chandrakant Thorat":{"D2DDHUDHU6266":"Prakash Sahebrao Borase,Ronakkumar  Lotan Thakre","D2DDHUDHU6265":"Mukund Dhanraj Patil,Jitendra Jivan Mohite","D2DDHUDHU6259":"Dipak  Givind Jadhav,Saiyad FaizAli JakirAli","D2DDHUDHU5980":"Piyush Dilip Gunjal,Pravin  Mohan Chavhan","D2DDHUDHU5669":"GANESH BHIKA WANI,Chetana  Ganesh Wani"}}},"YAVATMAL":{"MMU Camp":{"Ganesh  Gambhir Gedam":{"MMU0005221":"AMISHA  CHARDE,PALLAVI   ADE"}},"DOOR TO DOOR":{"Ashwini Rupesh Jaiswal":{"D2DYAVYAV6779":"MANSA  RAJU NAVHATE,Siddhi Raju Khandalkar","D2DYAVYAV6562":"Om Bandu Hanumante,Rutika Gopal Khamankar","D2DYAVYAV6447":"Pratiksha Pandurang Milmile,Vaishnavi Pandhari Ghugul","D2DYAVYAV5648":"NIKOO   JADHAV,GAYATRI RUPESH JAISWAL","D2DYAVYAV3613":"POOJA  JAYRAM SAUDE,Neha  Suresh Tamboli","D2DYAVYAV3611":"JAYSHREE ASHOK LINGARWAR,TEJAS  KISHOR TAJANE","D2DYAVYAV3609":"Anshri Indrabhushan Anake,Rahul Laxman Tekam"},"GAURI PRABHAKAR KADAM":{"D2DYAVYAV6680":"Shital Dinesh Marathe,DEVESH RAJENDRA DAMBHARE","D2DYAVYAV6006":"SAGAR KUNDAN PAWAR,PAWAN MAROTI RATHOD","D2DYAVYAV5804":"MANISHA  PANDHARE,SNEHA MAHESH KANDEKAR","D2DYAVYAV5483":"VAISHNAVI   JADHAV,GANESH   RATHOD","D2DYAVYAV5342":"SURAJ  RATHOD,PUSHPAM  HARI RATHOD","D2DYAVYAV3637":"SAMIKSHA  MAHENDRA BANGADE,MANOJ  KISAN JADHAV"},"KAJAL DASHRATH JAISWAL":{"D2DYAVYAV6656":"Sunil Lakhram Ade,BHIMRAO SANTOSH SIRSAT","D2DYAVYAV6574":"Monali Prabhakar Gudadhe,Amit Janardhan Manekar","D2DYAVYAV6573":"Neha  Awadhut Dhokane,SNEHAL SANJAYRAO BAKKAR","D2DYAVYAV6490":"NAMRATA GAJANAN DONGARWAR,KALYANI VASUDEV CHAUDHARI","D2DYAVYAV6450":"JOTSNA CHANDU CHAVHAN,SHARAD TARASING RATHOD","D2DYAVYAV6431":"MAHESH   RATHOD,HARIOM SUBHASH RATHOD","D2DYAVYAV5563":"YASH  JAMODE,PRITAM   RAUT","D2DYAVYAV5138":"VAIBHAV   YENKAR,ROHAN   UCHEGAONKAR"},"ADITYA  GAJANANRAO GULHANE":{"D2DYAVYAV6443":"SHUBHAM   TATEWAR,Radha Sharadrao Ashradwar","D2DYAVYAV6428":"PALAK DINESH NANDPATEL,RUTHVIK PRAKASH BODKHE","D2DYAVYAV6251":"MACHAGANDHA DNYANESHWAR SIDAM,SHRADDHA SUNILRAO JAMDAR","D2DYAVYAV3923":"Paresh  Mohad,Prachi  Raju Thakare","D2DYAVYAV3922":"VIJAYA JAGDISH JAISWAL,RANI  SAKHARAM DAFAL","D2DYAVYAV3919":"KEDITI DINESH NANDPATEL,ADITI  DINESH NANDAPATEL"},"YASH  ASHOKRAO KHANDRE":{"D2DYAVYAV6433":"NISHANT  DIPAKRAO KADAM,ARJUN GANESH THAKARE","D2DYAVYAV6432":"VISHAL SUDHAKAR CHAVHAN,PRAVIN SHIVAJI MASKE","D2DYAVYAV6201":"SAURABH  PANKAJ ABHAM,PRASHIK DNYANESHWAR SHENDE","D2DYAVYAV6200":"RAJANIGANDHA  GANESH LADKE,GANESH NARAYAN LADKE","D2DYAVYAV5145":"VAIBHAV  VIJAY PAIKRAO,YOGESH  RATHOD","D2DYAVYAV4240":"Diksha Laxman Sawate,SIMA  SAWATE","D2DYAVYAV4001":"SAGAR  GAJANAN RAUT,MOHAMMAD  SALIM","D2DYAVYAV1388":"Bharti Vinayak Kharode,Roopali Ramesh Misale"},"VISHAKHA  PANDHURANG KARE":{"D2DYAVYAV6397":"JAYA  DNYANESWAR ADE,NIKITA   LANJEWAR","D2DYAVYAV6299":"DATTA BALRAM CHAVHAN,PAYAL KAMRAJ JADHAO","D2DYAVYAV6126":"SAKSHI RAJESH TEKAM,SANKET RAJESH TEKAM","D2DYAVYAV5349":"MOHAMMADAMIN  PATLEWALE,IMRAN   NAURANGABDE","D2DYAVYAV4503":"ROHIT Manohar PATIL,ARTI  PATIL"},"AYUSH  SUNIL WADADKAR":{"D2DYAVYAV6326":"MOHANDAS   GAIBHARE,SHRADDHA  PARIPAGAR","D2DYAVYAV6283":"PRASAD PRAMODRAO HIWASE,TEJAS ASHOK SULBHEWAR","D2DYAVYAV5803":"MAYURI   BAMBORDE,VIJAYALAKSHMI MAROTI CHANDEKAR","D2DYAVYAV5422":"SHREENANDAN   BORGAONKAR,SHAIKH SAJID MAHEBUB","D2DYAVYAV5335":"Roshani  Raju Ganvir,DEVYANI  ADKINE","D2DYAVYAV4963":"ASHWINI   KARALE,YAMINI   JOSHI","D2DYAVYAV4353":"Janhavi Maroti Tatewar,PALLAVI  PRABHUDAS HARE","D2DYAVYAV4351":"GUJAN PRABHAKAR MADAVI,ABHISHEK SANJAY SALAR"}}},"JALNA":{"MMU Camp":{"ASHWINI Arun Jadhav":{"MMU0005157":"Amarpali  Salve,Neha   Zine"}},"DOOR TO DOOR":{"VISHAL VISHNU WAYAL":{"D2DJALMAN2506":"KRUSHNA BALASAHEB PHULARI,NADIM ALIM SHAIKH","D2DJALJAL6352":"ANKITA HARIBHAU SAGADE,Puja Vishwanath Korade","D2DJALJAL5937":"Pradip  Rajbinde,sachin  khomane","D2DJALJAL4733":"MUKUND RAMESHWAR THOMBARE,Anil  Kakde"},"AJAY SIDDESHWAR KANTULE":{"D2DJALJAL6781":"Dnyaneshwar Ashokrao Gavhane,VISHVAJIT  ASHOKSINGH RAJPUT","D2DJALJAL6739":"Swapnil Ashok Maske,Sopan Haribhai Mite","D2DJALJAL6689":"Saurabh   Pandhare,Saurabh   ghodke","D2DJALJAL6688":"Ganesh   Sagute,AMIR NASIR SHAIKH","D2DJALJAL6474":"AKSHAY DEVRAO GANJALE,AFROZ MOHIT DESHMUKH","D2DJALJAL6418":"Nikhil   Pawar,Nitin Ganesh Pawar","D2DJALJAL6185":"VAIBHAV SIDHHESHWAR SHINDE,Siddheshwar  Barsale"},"SANDIP  JADHAV":{"D2DJALJAL6691":"PATHAN AFZAL KHAN AKHTAR KHAN,Dhananjay  kardel","D2DJALJAL6690":"GANESH SUBHASH SHEWALE,SACHIN KAILAAS KHARAT","D2DJALJAL6209":"BHARAT SANTOSHRAO KHANDARE,Akshay   Karle","D2DJALJAL5685":"Ankush  Jamunde,Krushna   Jamunde","D2DJALJAL5684":"SAPNA  SHANKAR FOLANE,Laxmi   Khandagale","D2DJALJAL5672":"Tejaswini   Panpatil,Shubham Pandharinat Mirkar","D2DJALJAL4610":"Pathan  Mahebubkhan,Shaikh Muhammad Wajed","D2DJALJAF2459":"MOHAMMAD ARSHAD ABDUL QADEER SHAIKH,PATHAN NAJMUSSAQIB KHAN SHER KHAN"},"Pallavi Laxman Thakare":{"D2DJALJAL6419":"SHARAD PRAKASH CHAUDHARI,MAYUR VISHNU JAGTAP","D2DJALJAL5997":"ARJUN BABASAHEB DHORKULE,SHANKAR SUBHASH KOLTE","D2DJALJAL5243":"MOHD  FASIYODDIN BADRUDDIN,MUQEEM   KHAN","D2DJALJAL2094":"DNYANESHWAR TANAJI TUMMEWAR,SANDHYA DNYANESHWAR TUMMEWAR"},"Rahul Prakash Chaudhari":{"D2DJALJAL6179":"AMOL   PAWAR,GANESH  KAKDE","D2DJALJAL6079":"Santosh Bhausaheb Padol,GOPAL KAILAS SHAHAGADKAR","D2DJALJAL5244":"KISHOR   DHAGE,MAHESH   RATHOD","D2DJALJAL2854":"GAJENDRA RUSTUM RATHOD,AKASH RAMESH NIRMAL"}}},"SINDHUDURG":{"MMU Camp":{"Harshvardhan Sadashiv Kalelkar":{"MMU0005148":"Preeti  Ganesh Parab,Disha Dipak Palkar"}},"DOOR TO DOOR":{"Gaurav  Shivshankar Loke":{"D2DSINTAL6677":"Ramchandra Shantaram Loke,Chaitanya Chetan Tarkar","D2DSINTAL6676":"Srushti Gaurav Loke,Nikhil Anant Acharekar","D2DSINTAL6504":"Shraddha Narayan Kadam,Anvita Avinash Kadam","D2DSINTAL5710":"Manjiri Bhikaji Tambe,Suchita Sunil Thotam"},"Harshvardhan Sadashiv Kalelkar":{"D2DSINKUD6640":"Akshay Bhikaji Parab,Arati Mahesh Patil","D2DSINKUD6520":"Pujak Naresh Gawade,Rebecca Robert Fernandes"}}},"AKOLA":{"MMU Camp":{"ANAND VIJAY RAUT":{"MMU0005076":"SHABANA  ZAHEER,BHARATI   CHOUDHARI"}},"DOOR TO DOOR":{"GAURAV  VILAS KHAWANE":{"D2DAKOAKO6778":"MOHAMMAD UMAIR MOHAMMAD MUKHTAR,MUZAMMIL  JAMEEL KHAN","D2DAKOAKO6625":"USAMA MASHKUR KHAN,AWAIS RAZA KHAN RAHIM KHAN","D2DAKOAKO6557":"PRIYANKA  ROHIT BANSOD,ROHIT MAHADEO BANSOD","D2DAKOAKO6385":"NEHA   BHIMAKR,KHUSHI SUNIL BHIMKAR","D2DAKOAKO5752":"REHAN  NQUIM SYED,Mohd Aatif Abdul Mujeeb","D2DAKOAKO4944":"AMOL  GHUGE,GANESH   GHUGE","D2DAKOAKO4842":"APURVA VASANT MANKAR,KARAN  VITTHAL KAWALE","D2DAKOAKO3978":"Aniket  Madhukar Deshmukh,RASHMI  SARNAYK","D2DAKOAKO1736":"Mohini  Rajesh Raut,Gayatri Sheshrao Kuchkar"},"Sagar Gajanan Mhaisane":{"D2DAKOAKO6776":"ROSHAN SUPADA WAWGE,ANAND GANESH DHOLE","D2DAKOAKO6502":"SHAIKH SAFEE UR RAHMAN SHAIKH,MOHD SIDDIQUE ASAD MOHD ATIQUE","D2DAKOAKO6463":"SHARDA  VASANT CHAURIWAR,VIJITA VIJU SHIRKE","D2DAKOAKO6269":"FAIZAN  ISMAIL KHAN,MOHAMMAD SAAD MOHAMMAD AAQUIL","D2DAKOAKO4834":"ASIF  ANIS KHAN,AMIR   KHAN","D2DAKOAKO4816":"Pallavi Kisan Girhe,SHIKANT  PRAMOD KOLTKAR","D2DAKOAKO4466":"DINESH  Pande,PAVAN  TAYADE","D2DAKOAKO2900":"RUPALI   SANDIP SHEGOKAR,SHILPA  NARAYAN MAISANE"},"Vaibhav  ASHOK Telgote":{"D2DAKOAKO6766":"MOHAMMAD UMAIRODDIN MOHAMMAD IRFANODDIN,ARAFAT  SHARIQUEISMAIL KHAN","D2DAKOAKO6606":"SONI  FRANCIS MUJMULE,SNEHA FRANCIS MUJUMALE","D2DAKOAKO6589":"Vivek    More,CHIRAG  SHARMA","D2DAKOAKO6501":"PRATUSH   KHANDARE,VAIBHAV MADHUKAR JAVANJAL","D2DAKOAKO6125":"RUSHIKESH DILIP INGLE,VIVEK SURESH BOCHARE","D2DAKOAKO5935":"ABDUL  ILYAS,TANVEER BAIG TAJAMMUL BAIG","D2DAKOAKO5456":"MUZAMMIL  KALEEM AHMED,SHOEB   KHAN","D2DAKOAKO5327":"SANGHADEEP PANDURANG AMBHORE,Chaitanya Sadanand Ambhore"},"SNEHA SADANAND KHARODE":{"D2DAKOAKO6701":"AMITKUMAR   WAGHMARE,VRUKSHAVALLI RAVINDRA BHAGAT","D2DAKOAKO6627":"MOHAMMAD MUSTAFIZUDDIN MOHAMMAD,MOHAMMED RIZWAN MOHAMMAD ZAKIR","D2DAKOAKO6467":"Kusum GAJANAN Yedke,DARSHANA  MHAISANE","D2DAKOAKO6466":"ARCHANA  MANOJ Shegavkar,VARSHA VITTHAL MUTHAL","D2DAKOAKO5993":"ABHISHEK  SANTOSHRAO ADHAU,BHUSHAN GAJANAN DAHALE","D2DAKOAKO5825":"Shital  Shirsat,RADHIKA RAMESH SARDAR","D2DAKOAKO4528":"Vaishnavi Sahadeo Hiwarkhede,ABHISHEK  VISHNU SAWARKAR","D2DAKOAKO1567":"SUSHAMA  AMIT WAGHMARE,Ashwini Mohan Aathvale"},"Mohd Ayub Mohd Rafique":{"D2DAKOAKO6626":"MOHAMMAD   ARSHADABDULRAH,ABDUL   KARIM"}}},"Nashik":{"MMU Camp":{"Parasram Mugaji Jegade":{"MMU0004266":"Tejaswini Vitthal Dhule,Vidya Santosh Bhambare"}},"DOOR TO DOOR":{"ADESH SHIVNATH KOLHE":{"D2DNASNAS6780":"Narendra Nana Shinde,Nilesh  Arjun Valvi","D2DNASNAS6685":"Mahesh  Sunil Khaimar,Akshay  Laxman Patil","D2DNASNAS6604":"Mohammad Sameer Abdul Raheman Pinjari,Karan  Rajendra Pawar","D2DNASNAS6603":"Bhushan  Laxman Sabale,Anam Nihal Shaha","D2DNASNAS6602":"Vrushali Prakash Thakare,Dipali  Balasaheb Tate","D2DNASNAS6601":"Vishal Vedu Pawar,Arpita  Pratap Gavit","D2DNASNAS6600":"Pervez  Israruddin Shaikh,Kirankumar Ravindra Thakare","D2DNASNAS5815":"Vaibhav  Dharmaraj Wagh,Sandeep  Nandkumar Chandwadkar"},"Yuvraj Pradip Solunke":{"D2DNASNAS6635":"Kiran Sunil Patil,Harshad Vijay Gudhekar","D2DNASNAS6629":"Ravindra Sampat Khurde,Rakesh Suresh Shinde","D2DNASNAS6628":"Nilesh  Rajaram Bhoye,Swaraj Sanjay Sharma","D2DNASNAS6492":"Amol Ramesh Khairanar,Samadhan Bhavulal Mane","D2DNASNAS6113":"Revannath Sadashiv Dalavi,Alfiya  Azomoddin Sayyed","D2DNASNAS6090":"Saurabh Ashok Thenge, Akshada  Bhausaheb Gangurde","D2DNASNAS5891":"Darshan Santosh Tehale,Sachin Ramesh Saindane","D2DNASNAS1433":"Shaikh  Samin Ayyub,Pathan Bhushra Ayyub"},"NA":{"D2DNASNAS5532":"Anuj  Arun Devghare,Gauri Ambadas Shinde"},"Kiran Ashok Shinde":{"D2DNASMAN6721":"Satish Namdev Sonawane,Aditya  Chandrakant Jadhav","D2DNASMAN6449":"Yash  Anil Lunawat,Shubham Dattu Khatal","D2DNASMAN6235":"Suraj Dipak Pardeshi,Adnan Jabir Shaikh","D2DNASMAN5624":"Aarti Shivaji Sonawane,Vaibhav  Jalindar Ghadge","D2DNASMAN5254":"Rahul  Pandurang Paithankar,Dnyaneshwar Bhausaheb Bhilore","D2DNASMAN5031":"Shyam Bhausaheb Ahire,Vaishali  Kantilal Gangurde","D2DNASMAN3968":"GORAKH SAMPAT SADAGIR,Ganesh Walmik Solapure","D2DNASMAN2708":"SAHIL TANVEER SHAIKH,ARSHAAN SANVAR PATHAN"},"Pawan Sunil Ahire":{"D2DNASMAL6673":"Manoj  Subhash Khairnar,Chetan Nitin Deore","D2DNASMAL6672":"Bhushan Santosh Gangawane,Bhushan  Santosh Jadhav","D2DNASMAL6298":"Shubham Bhausaheb More,Aniket Karbhari More","D2DNASMAL6228":"Rohit Ashok Deore,Saurabh Ravindra Deore","D2DNASMAL6053":"Rutik Samadhan Suryawanshi,Devanand Karbhari Nikam","D2DNASMAL5736":"Yash Ramesh Sonawane,Digambar Sahebrav Nikumbh"},"Siddharth Kacharu Pagare":{"D2DNASMAL6668":"SACHIN  BHARAT THAKARE,Siddharth Hari Sonawane","D2DNASMAL6595":"YASHODIP  RAMESH PAWAR,Dhananjay Sham Pawar","D2DNASMAL6517":"Akshay Dnyaneshwar Khairnar,Raj Gabbar Pawar","D2DNASMAL6448":"Prajwal Ravindra Jadhav,Jayvardhan Padmsangh Bagul","D2DNASMAL6115":"Rushikesh Jibhau Deore,Kalpesh Pravin More","D2DNASMAL5782":"Vijay Pandit Dasnur,Pavan Vijay Mohite","D2DNASMAL5655":"Bhavesh Sarjirao Pawar,Vijay Uttam Jagnar","D2DNASMAL5470":"GANESH  VITHOBA PAGARE,Hrishikesh Vasant Pagare","D2DNASMAL5134":"Leena Vijay Borale,Onkar Kishor Ingale","D2DNASMAL4507":"CHETAN  NATHA ANAWADE,Mayur Tukaram Pardeshi","D2DNASMAL4384":"Hemraj Ravindra Sonawane,Tushar Kailas Namekar","D2DNASMAL3018":"SHAIKH AZHARUDDIN  SHAIKH RAFIK,MOHAMMED SHAKEB SHAUKAT HUSAIN"}}},"Dharashiv":{"MMU Camp":{"AKASH PANDURANG ANERAO":{"MMU0004250":"ASHISH   KHALDE,GAURAV   RATHOD"}},"DOOR TO DOOR":{"Ajay  Arun Pavale":{"D2DDHAOSM5780":"RUSHIKESH MAHINDRA HADULE,SHIVPRASAD ABASAHEB JAGTAP","D2DDHAOSM4363":"TOFIK  TAMBOLI,PRATHMESH  DONGE","D2DDHAOSM4263":"OM  JANAK KASBE,HARSHADA  BHAGWAN PANDIT","D2DDHADHA6684":"Maharudra Balasaheb Nakshe,Shubham Shivaji Gambhire","D2DDHADHA6596":"Govind Kantaram Shinde,Abhishek Asaram Shinde","D2DDHADHA6451":"Dnyaneshwar Madhukar Sakhare,Ramkrushna  Laxman Kumbhar","D2DDHADHA6336":"SUSHANT  SURESH BAGADE,ROHIT RAVINDRA DESHMUKH","D2DDHADHA6335":"SANNY  SURESH BAGADE,Pranali santosh Vare","D2DDHADHA6211":"NOUFIL  SIKALKAR,Owes Babarkhan Pathan","D2DDHADHA6099":"REHAN JAFAR SHAIKH,Saurabh Mahavir Surwase","D2DDHADHA5981":"BALU  GOPINATH SATPUTE,SAMARTH PANDURANG MORE"}}},"GADCHIROLI":{"MMU Camp":{"Vaibhav Dilip Lakade":{"MMU0003691":"VAISHANAVI  RAVIPRAKASH ABHARE,PRITI JAGDISH KOLTE","MMU0003607":"Susmita  Kshirsagar Dange,Mohini  Gautam Karade"}},"DOOR TO DOOR":{"Pallavi Amol Mulankar":{"D2DGADGAD6679":"Varsha Ramesh Rajurkar,Shital Rushi Mitpalliwar","D2DGADGAD6536":"Vaibhav  Rushidev Pipare,Chandrashekhar  Santosh Mohurle","D2DGADGAD6238":"Raj Giridhar Dighore,Vanshaj  Vinod Kalbandhe","D2DGADGAD5103":"Vandana Uddhav Pipare,Uddhao Ramdas Pipare","D2DGADGAD5102":"Trupti Vikas Fule,Pratiksha  Chandramohan Tirpude","D2DGADGAD4691":"Vishal Dharmpal Khaire,Bhagwan Atmaram Kapgate"}}},"WARDHA":{"MMU Camp":{"DIPALI DARSHAN RAUT":{"MMU0003634":"Sharada  Ganesh Pawar,Durga  Prakash Khodankar"}},"DOOR TO DOOR":{"PRINCY  VIKAS UMRE":{"D2DWARWAR6424":"Rutik  Vishnu Kambale,Sanket  Diliprao Hadke","D2DWARWAR6102":"SADIYARAHEMAT SATTAR SHEIKH,Ketaki  Ramesh Gujar","D2DWARWAR5240":"Adesh  Divakar Sirsat,Akshay   Sanjay Bontawar","D2DWARWAR3603":"SHUBHAM  ANIL BHONGADE,Pranali Sudhakar Bhoyar"},"Nilesh  Bhimraoji Malgam":{"D2DWARWAR6030":"Parvin Babaraoji Patil,Sumedha  Kamlesh Meshram","D2DWARWAR5519":"Rashmi  Rajesh More, Gaurav  Raghunathji Bhoyar","D2DWARWAR4926":"Yogesh Indal Rathod,Shweta Krusnaji Gaykwad","D2DWARWAR4548":"Piyush Suresh Chandankhed,Aniket  Rajendra Mahakalka"},"MEHAR RAMBHAUJI CHAUDHARI":{"D2DWARWAR5518":"Shradha Raju Bokade,Prajakata  Amolrao Mahakalkar","D2DWARWAR5242":"Sameer  Prakash Kamble,Rahul  Ashokrao Tadas","D2DWARWAR3497":"Rahul Lonkar Jadhao,Diksha Vilasrao Surkar","D2DWARWAR2805":"KHUSHI MANOHAR JAMANKAR,Rushikesh Viothalrao Jamannkar"},"Nikita Ramuji Dhande":{"D2DWARHIN6363":"Samiksha  Raju Timande,Harish  Pitambar Kalamkar"},"VISHAL  PRAKASH MANDAOKAR":{"D2DWARHIN3113":"BHOOMIKA  SHYAM SOREMARE,Kalyani Sachin Patil"},"Ashish Sandip Gayakwad":{"D2DWARARV6095":"Mileend Yuvraj Dahat,Shiwani Sanjayrao Dahake","D2DWARARV6093":"Sarika Prakashrao Nageshwar,Saniya Akhtar Sayyad","D2DWARARV5117":"NIKITA VASANTRAO KAIKADE,Nikita Manohar Pokale","D2DWARARV3903":"Minakshi  Rajesh Sarate,Sakshi  Pramodrao Raut"}}},"BHANDARA":{"MMU Camp":{"Akash Ganeshnath Patle":{"MMU0003537":"NANDA  VISHNU PADOLE,NANDA  MALIKCHAND KOSARKAR","MMU0003474":"Meghna Amrut Bhoyar,Prajakta Krishna Kamble"}},"DOOR TO DOOR":{"Nainika Tejram Wanjari":{"D2DBHABHA6758":"Tushar Kartik Urkude,Priya  Shivshankar Gajbhiye","D2DBHABHA4413":"Hitesh Lalji Kore,Dipak Madhukar Sawarbandhe"},"Aditya Ramchandra Bhoyar":{"D2DBHABHA6494":"Anjali Chainlal Masarke,Ayushi  Mukesh Bhardwaj","D2DBHABHA5836":"Kshitij Vikas Hatwar,Tejshri  Kailas Deshmukh","D2DBHABHA4808":"Dipali  Haridas Karemore,Megha  Vijay Malewar","D2DBHABHA4115":"Pradumnya  Gopichand Baraskar,Amit  Kavdu Tumsare","D2DBHABHA3278":"Mayuri Gopichand Halmare,Swati Satish Thawkar","D2DBHABHA1339":"MOHIT VIKAS HATWAR,MUNESHWARI RAMKRUSHNA KAPSE"},"Reshma Homraj Kapgate":{"D2DBHABHA6070":"Yamini  Motilal Nagpure,Pragati Mohan Wadhai","D2DBHABHA5246":"Snehal  Rajkumar Rinait,Jatin  Sanjiv Tembhurne","D2DBHABHA4941":"Haushilal  Asaram Baraskar,Prajyot  Jagdish Raut","D2DBHABHA4674":"Kaveri Rajesh Nagalwade,Shubhangi  Ramesh Ukey","D2DBHABHA3427":"Puja Tularam Gajbe,Bhagyashri Rajkumar Bhute","D2DBHABHA1402":"Dipali Sanjay Borkar,Samta Sanjay Borkar"}}},"CHANDRAPUR":{"MMU Camp":{"ASHISH VASANTRAO CHAWARE":{"MMU0003535":"Ashwini  Shankar Asutkar,Pradnya Tularam Bhaisare"}},"DOOR TO DOOR":{"Hina Baldarkha Pathan":{"D2DCHAWAR3806":"Priya Ravi Tikhat,Sakshi Trishul Potdukhe","D2DCHACHA6746":"Sachin Madhukar Kamdi,Vaishnavi  Mahaling Kanthale","D2DCHACHA6630":"Parvin Shukracharya Teltumbade,Vaibhav  Vijay Hadgekar","D2DCHACHA6558":"Prititai Pandurang Satpute,Arpita  Subhash Misal","D2DCHACHA6252":"Amit  Gautam Sahare,Pallavi Arvind Bahade","D2DCHACHA6234":"Pradip Tarachand Ramteke,Vrundavani Bhojraj Bansod","D2DCHACHA5886":"Priyanka Rameshwar Bahurashi,Rohan  Rameshwar Bahurashi","D2DCHACHA5885":"Avinash  Prakash Madankar,Suraj  Rajeshsingh Bais","D2DCHACHA5486":"Kshitij  Kamlakar Maraskolhe,Tejas Deepak Narwade","D2DCHACHA5251":"Shital  Jaypal Dongare,Jaypal  Gajanan Dongare","D2DCHACHA4793":"Vaibhav   Shankar Fad,Shahid Shabbir Sheikh","D2DCHACHA3636":"Aditya  Gunvant Charlikar,Ritesh  Vijay Ade"},"VISHAL  PRAKASH MANDAOKAR":{"D2DCHACHA6551":"Pranay  Ramesh Barsagade,Ramjan  Abdul Sheikh","D2DCHACHA6510":"Satyeshwar  Raja Tulankar,Tanushree   Devrao Ramgunde","D2DCHACHA6509":"GIRIJA  NAMDEO BHAJIPALE,Anjali Rajesh Dambhare","D2DCHACHA6508":"AJAY  PRAKASHRAO MANDAOKAR,Nikhita Vitthal Chawre","D2DCHACHA6507":"Nayan Mahadev Dhavale,Aniket Kisnaji Ghode","D2DCHACHA6506":"Yogesh Arun Date,Dipali Arunrao Chaudhari","D2DCHACHA6465":"Sachin Rohidas Ade,Sonu Sunil Khamankar","D2DCHACHA6464":"Pranay Bhaskar Badki,Aniket  Suraj Ramteke","D2DCHACHA5887":"Sagar Sanjay Shreshti,Akanksha  Jagrup Shrivas"}}},"NANDED":{"DOOR TO DOOR":{"Mohini  Mohanrao Waghmare":{"D2DNANNAN6660":"Mayawati  Chandramuni Gaykwad,SAHEBRAO   GUNDALE","D2DNANNAN6325":"DHANRAJ  KHANSOLE,PRAMOD  SURYAWANSHI","D2DNANNAN6075":"SATISH  SAKHRE,RUSHIKESH SANJAY INGOLE","D2DNANNAN5969":"ASHISH   GIRI,NISHANT  Kamble","D2DNANNAN5355":"NITEEN   KAMBLE,OMKAR   SHENDGE"},"PRAKASH  MALHARI SONKAMBLE":{"D2DNANNAN6598":"SYED FAIZAN ALISYED GAFFARALI,Shaikh Taufeeq  Ahmed Ismail","D2DNANNAN6512":"Vaibhav  Kailasrao Kadam,VAIBHAV BALAJI SONKAMBLE","D2DNANNAN5842":"RITESH   PAWADE,Abdul Hujefa Abdul Wajeed","D2DNANNAN5732":"Omkar  Laxman paratkar,PRANAY   SURYAWANSHI","D2DNANNAN5613":"Vishal  Balwantrao Wadje,SHIVAM PRABHAKAR KOMPALWAR","D2DNANNAN5541":"SAINATH   MANCHALWAD,DNYANESHWAR   PARSEWAD","D2DNANNAN5285":"Mirza Rahman  MirzaImran Baig,MALSAKANT  GARODE","D2DNANNAN4712":"MOHAMMED  ANSARI,MOHAMMED  AWAIS WAJEED","D2DNANNAN4675":"AJAY  BABURAO SARODE,SHYAM  UTTAM WAGHMARE","D2DNANNAN4364":"MUZAKKIR  QUASIM SHAIKH,MOHAMMED  KHAJA"},"Mohammed Azeem  MohammedAziz":{"D2DNANNAN6578":"Shaikh Shoeb  Shaikh Shafi,ASHISH SANJAY AADE","D2DNANNAN6570":"ABDUL   SHAFI,SHIVAM GOPINATH PATIL","D2DNANNAN6452":"Shivanand  Sanjay Waghmare,SACHIN  RUPSING JADHAV","D2DNANNAN6038":"Akash  Suryawanshi,Saiprasad  Waghmare","D2DNANNAN5706":"Kapil  Devidas Donerao,Sudarshan   Balaji Donerao","D2DNANNAN5617":"JUGALSINH   THAKUR,Aawej Shabbir Shaikh","D2DNANNAN5317":"Shubham Namdev kamble,SHAIKH  ABUL FAROOQ"},"Sainath  Satwaji Hambrde":{"D2DNANNAN6538":"Sanket  Raghunath Kadam,Rushikesh Vyankati Kamble","D2DNANNAN6415":"Gajanan dnyanoba More,Rohit Ramkrishna Tanmane","D2DNANNAN6323":"Shabanam Khatum  Amir Shaikh,vishal  ghodge","D2DNANNAN6322":"Balaji  Shinde,Nilesh  Arvind Kamble","D2DNANNAN5945":"SUMIT SUNIL UPPE,Suraj  Vikram Mundkar","D2DNANNAN5851":"SHAIKH SHOYAB MAHEBOOB,SHIRADKAR DNYANESHWAR TUKARAM","D2DNANNAN5833":"NITESH  RAJU GOKHALE,PAVAN MEGHAJI GAIKWAD","D2DNANNAN4040":"SANTOSH  SAKHARAMRAO GOTRAL,SUDHAKAR  GANESH DOIJAD","D2DNANNAN2871":"Yojana  Dhananjay Bhalerao,MADHAV  SHANKAR SHELKE","D2DNANMUK2776":"Aditya  Vishwanath Panchal,Sailani  Rasulkhan Pathan"},"NA":{"D2DNANNAN4160":"Yogesh  Kupte,Narayan  Hatvegale","D2DNANNAN3966":"Sairaj  Ashok Gavvalwar,Shaikh Tajid  Shaikh Latif"}}},"KOLHAPUR-ICHALKARANJI":{"DOOR TO DOOR":{"Satyam   Mahadik":{"D2DKOLKOL6764":"Taisin   karadi,SANIYA   MUJAWAR","D2DKOLKOL6762":"Sourabh Anil Khot,Shrikant  Digambar Amane","D2DKOLKOL6734":"SANIKA RAMCHANDRA KAMBLE,Sadiya   Abdagiri","D2DKOLKOL6491":"Amruta Sagar Patil,NEHA   KANTHIKAR","D2DKOLKOL5875":"Rohini  Chandrakant Tonape,Mayuri Chandrakant Gayakawad","D2DKOLKOL5869":"Shamali kiran kamble,Supriya Rajendra Bansode","D2DKOLKOL5306":"FATIMA   GAVANDI,KOMAL   TARDALE","D2DKOLKOL5305":"KOMAL   NAIK,ASAWARI   GHEWARI","D2DKOLKOL4899":"ASHWINI  TIKONE,SMITA   CHIVATE","D2DKOLKOL4859":"Nivedita  Nivas Bhakare,DIVYA   RANBHARE"},"SNEHAL RAMESH SATPUTE":{"D2DKOLKOL6645":"Rohit Baban Kale,Sarika Swapnil Kamble","D2DKOLKOL6620":"Masayabi  Bashir Khatib,Riya Sambhaji Koli","D2DKOLKOL6619":"Rutuja  Hemant Kamble,PARASHRAM   ANNAPPA SHINGADE","D2DKOLKOL6618":"Abhishek Bhauso Ankale,Aditya Avdhut Amane","D2DKOLKOL6293":"VAIBHAVI SANDIP SASWADE,DHANSHRI BALGONDA BORGAVE","D2DKOLKOL6101":"ASHITOSH  SUNIL KAMBLE,Juber Mansur Bijali","D2DKOLKOL5977":"saurabh  ajeet kamble,Farjan   Sanadi","D2DKOLKOL5871":"AMIT   MOHITE,Sameer Bakas Gavandi","D2DKOLKOL5642":"Amruta  Sambhaji Chavan,Sonali Suresh Kamble","D2DKOLKOL5426":"PRATIKSHA   HALADE,HINAKAUSAR   ATTAR","D2DKOLKOL5323":"Sangramsingh  Dilip Shinde,SANDESH   MANE","D2DKOLKOL4965":"NUTAN   DHALE,Reshma   Suryawanshi"}}}}
;

// ============================================================
// CONSUMABLE ITEMS (from Excel: Consumable Table sheet)
// ============================================================
const consumableItems = [
  'EDTA Tube',
  'Gel Tube',
  'CW Barcode',
  'Glucometer Strip (Pcs)',
  'Vacutainer Needle (Pcs)',
  'Gluco Lancet (Pcs)',
  'Cotton Roll',
  'Alcohol Swab (Pcs)',
  'CW TRF Book',
  'Mouth Piece (Pcs)',
  'Sticking Plaster (Pcs)',
  'Gloves (Pcs)',
  'Fine Tip Marker',
  'Tourniquet',
  'Black BMW Bag',
  'Yellow BMW Bag',
  'Red BMW Bag',
  'Vacutainer Holder',
  'T2T Barcode'
];

// ============================================================
// STATE
// ============================================================
let currentCampType = 'Regular Camp';
let isSubmitting = false;
let receivedClosingRequired = true;

// ============================================================
// DOM REFERENCES
// ============================================================
const districtSelect    = document.getElementById('districtSelect');
const campTypeHidden    = document.getElementById('campTypeHidden');
const regularSection    = document.getElementById('regularCampSection');
const dependentSection  = document.getElementById('dependentSection');
const coordinatorInput  = document.getElementById('coordinatorName');
const jasMasSelect      = document.getElementById('jasMasSelect');
const manualJasMasGroup = document.getElementById('manualJasMasGroup');
const manualJasMasInput = document.getElementById('manualJasMas');
const teamNoSelect      = document.getElementById('teamNoSelect');
const manualTeamNoGroup = document.getElementById('manualTeamNoGroup');
const manualTeamNoInput = document.getElementById('manualTeamNo');
const teamNameDisplay   = document.getElementById('teamNameDisplay');
const teamNameHidden    = document.getElementById('teamNameHidden');
const manualTeamNameGroup = document.getElementById('manualTeamNameGroup');
const manualTeamNameInput = document.getElementById('manualTeamName');
const consumableTbody   = document.getElementById('consumableTableBody');
const consumableTableEl = document.getElementById('consumableTable');
const trackToggle       = document.getElementById('trackReceivedClosing');
const trackHint         = document.getElementById('trackHint');
const consumableErrorEl = document.getElementById('consumableError');
const mainForm          = document.getElementById('mainForm');
const submitBtn         = document.getElementById('submitBtn');
const loadingOverlay    = document.getElementById('loadingOverlay');
const loadingMsg        = document.getElementById('loadingMsg');
const successCard       = document.getElementById('successCard');
const formWrapper       = document.getElementById('formWrapper');
const refIdDisplay      = document.getElementById('refIdDisplay');
const alertError        = document.getElementById('alertError');
const alertErrorMsg     = document.getElementById('alertErrorMsg');

// ============================================================
// INIT
// ============================================================
document.addEventListener('DOMContentLoaded', function() {
  buildConsumableTable();
  setReceivedClosingVisibility(trackToggle.checked);
  consumableTbody.addEventListener('input', handleConsumableInput);
  trackToggle.addEventListener('change', function() {
    setReceivedClosingVisibility(this.checked);
  });
  selectCampType('Regular Camp', document.querySelector('.camp-tab[data-value="Regular Camp"]'));
  districtSelect.addEventListener('change', onDistrictChange);
  jasMasSelect.addEventListener('change', onJasMasChange);
  teamNoSelect.addEventListener('change', onTeamNoChange);
  mainForm.addEventListener('submit', handleSubmit);
});

// ============================================================
// BUILD CONSUMABLE TABLE
// ============================================================
function buildConsumableTable() {
  consumableTbody.innerHTML = '';
  consumableItems.forEach(function(item, idx) {
    const tr = document.createElement('tr');
    tr.innerHTML =
      '<td><span class="sno">' + (idx + 1) + '.</span> ' + escapeHtml(item) + '</td>' +
      '<td><input type="number" name="opening_' + idx + '" id="opening_' + idx + '" min="0" placeholder="0" /></td>' +
      '<td class="col-received"><input type="number" name="received_' + idx + '" id="received_' + idx + '" min="0" placeholder="0" /></td>' +
      '<td class="col-closing"><input type="number" name="closing_' + idx + '" id="closing_' + idx + '" min="0" placeholder="0" readonly /></td>';
    consumableTbody.appendChild(tr);
  });
}

// ============================================================
// CONSUMABLE: AUTO CLOSING STOCK + RECEIVED/CLOSING TOGGLE
// ============================================================
function handleConsumableInput(e) {
  const match = (e.target.id || '').match(/^(opening|received)_(\d+)$/);
  if (match) updateClosingStock(parseInt(match[2], 10));
}

function updateClosingStock(idx) {
  const openingInp  = document.getElementById('opening_' + idx);
  const receivedInp = document.getElementById('received_' + idx);
  const closingInp  = document.getElementById('closing_' + idx);
  if (!closingInp) return;

  // When Received/Closing tracking is off, Closing stays at 0 (blank).
  if (!receivedClosingRequired) {
    closingInp.value = '';
    return;
  }

  const openingRaw  = openingInp ? openingInp.value : '';
  const receivedRaw = receivedInp ? receivedInp.value : '';

  if (openingRaw === '' && receivedRaw === '') {
    closingInp.value = '';
    return;
  }

  const opening  = openingRaw === ''  ? 0 : (parseFloat(openingRaw)  || 0);
  const received = receivedRaw === '' ? 0 : (parseFloat(receivedRaw) || 0);
  const sum = opening + received;
  closingInp.value = Number.isInteger(sum) ? sum : sum.toFixed(2);
}

function recalculateAllClosingStock() {
  consumableItems.forEach(function(_, idx) { updateClosingStock(idx); });
}

function setReceivedClosingVisibility(show) {
  receivedClosingRequired = show;
  consumableTableEl.classList.toggle('compact-mode', !show);

  if (!show) {
    consumableItems.forEach(function(_, idx) {
      const receivedInp = document.getElementById('received_' + idx);
      if (receivedInp) {
        receivedInp.value = '';
        receivedInp.classList.remove('error');
      }
    });
  }

  recalculateAllClosingStock();

  if (trackHint) {
    trackHint.textContent = show
      ? 'Visible & mandatory for all items'
      : 'Hidden — treated as 0 for all items';
  }

  if (consumableErrorEl) consumableErrorEl.classList.remove('visible');
}

// ============================================================
// CAMP TYPE SELECTION
// ============================================================
function selectCampType(campType, btn) {
  // Update tab styles
  document.querySelectorAll('.camp-tab').forEach(function(t) {
    t.classList.remove('active');
  });
  if (btn) btn.classList.add('active');

  currentCampType = campType;
  campTypeHidden.value = campType;

  if (campType === 'Regular Camp') {
    regularSection.classList.remove('hidden');
    dependentSection.classList.add('hidden');
  } else {
    regularSection.classList.add('hidden');
    dependentSection.classList.remove('hidden');
    refreshJasMasDropdown();
  }
  clearErrors();
}

// ============================================================
// DISTRICT CHANGE
// ============================================================
function onDistrictChange() {
  clearErrors();
  if (currentCampType !== 'Regular Camp') {
    refreshJasMasDropdown();
  }
}

// ============================================================
// REFRESH JAS/MAS DROPDOWN
// ============================================================
function refreshJasMasDropdown() {
  const district = districtSelect.value;
  const campType = currentCampType;

  // Map display campType to data campType keys
  const campTypeKey = (campType === 'D2D Camp') ? 'DOOR TO DOOR' : 'MMU Camp';

  // Reset downstream
  resetTeamNo();
  resetTeamName();
  hideManualJasMas();

  jasMasSelect.innerHTML = '<option value="">— Select JAS / MAS Name —</option>';
  jasMasSelect.disabled = true;
  teamNoSelect.disabled = true;

  if (!district) return;

  const districtData = masterData[district];
  if (!districtData || !districtData[campTypeKey]) {
    jasMasSelect.innerHTML = '<option value="">No data for this district &amp; camp type</option>';
    return;
  }

  const jasMasNames = Object.keys(districtData[campTypeKey]).sort();

  jasMasNames.forEach(function(name) {
    const opt = document.createElement('option');
    opt.value = name;
    opt.textContent = name;
    jasMasSelect.appendChild(opt);
  });

  // Add "Not Available in List" option
  const naOpt = document.createElement('option');
  naOpt.value = '__NOT_AVAILABLE__';
  naOpt.textContent = '— Not Available in List —';
  jasMasSelect.appendChild(naOpt);

  jasMasSelect.disabled = false;
}

// ============================================================
// JAS/MAS CHANGE
// ============================================================
function onJasMasChange() {
  clearErrors();
  resetTeamNo();
  resetTeamName();

  const selected = jasMasSelect.value;

  if (selected === '__NOT_AVAILABLE__') {
    showManualJasMas();
    showManualTeamNo();
    showManualTeamName();
    return;
  }

  hideManualJasMas();
  hideManualTeamNo();
  hideManualTeamName();

  if (!selected) {
    teamNoSelect.disabled = true;
    return;
  }

  const district = districtSelect.value;
  const campTypeKey = (currentCampType === 'D2D Camp') ? 'DOOR TO DOOR' : 'MMU Camp';
  const teamsObj = masterData[district][campTypeKey][selected];

  teamNoSelect.innerHTML = '<option value="">— Select Team No —</option>';
  teamNoSelect.disabled = false;

  Object.keys(teamsObj).sort().forEach(function(teamNo) {
    const opt = document.createElement('option');
    opt.value = teamNo;
    opt.textContent = teamNo;
    teamNoSelect.appendChild(opt);
  });

  // Add "Not Available" option
  const naOpt = document.createElement('option');
  naOpt.value = '__NOT_AVAILABLE__';
  naOpt.textContent = '— Not Available in List —';
  teamNoSelect.appendChild(naOpt);
}

// ============================================================
// TEAM NO CHANGE
// ============================================================
function onTeamNoChange() {
  clearErrors();
  const selected = teamNoSelect.value;

  if (selected === '__NOT_AVAILABLE__') {
    showManualTeamNo();
    showManualTeamName();
    resetTeamName();
    return;
  }

  hideManualTeamNo();
  hideManualTeamName();

  if (!selected) {
    resetTeamName();
    return;
  }

  const district  = districtSelect.value;
  const jasMas    = jasMasSelect.value;
  const campTypeKey = (currentCampType === 'D2D Camp') ? 'DOOR TO DOOR' : 'MMU Camp';
  const teamName  = masterData[district][campTypeKey][jasMas][selected] || '';

  displayTeamName(teamName);
  teamNameHidden.value = teamName;
}

// ============================================================
// DISPLAY TEAM MEMBERS
// ============================================================
function displayTeamName(teamNameStr) {
  if (!teamNameStr) {
    teamNameDisplay.innerHTML = 'Team members will appear here after selecting Team No.';
    teamNameDisplay.classList.add('empty');
    teamNameHidden.value = '';
    return;
  }

  const members = teamNameStr.split(',').map(function(m) { return m.trim(); }).filter(Boolean);
  teamNameDisplay.classList.remove('empty');
  teamNameDisplay.innerHTML = members.map(function(m) {
    return '<div class="team-member">' + escapeHtml(m) + '</div>';
  }).join('');
  teamNameHidden.value = teamNameStr;
}

// ============================================================
// RESET HELPERS
// ============================================================
function resetTeamNo() {
  teamNoSelect.innerHTML = '<option value="">— Select JAS / MAS Name first —</option>';
  teamNoSelect.disabled = true;
}

function resetTeamName() {
  teamNameDisplay.innerHTML = 'Team members will appear here after selecting Team No.';
  teamNameDisplay.classList.add('empty');
  teamNameHidden.value = '';
}

function showManualJasMas() { manualJasMasGroup.classList.remove('hidden'); }
function hideManualJasMas() { manualJasMasGroup.classList.add('hidden'); manualJasMasInput.value = ''; }
function showManualTeamNo() { manualTeamNoGroup.classList.remove('hidden'); }
function hideManualTeamNo() { manualTeamNoGroup.classList.add('hidden'); manualTeamNoInput.value = ''; }
function showManualTeamName() { manualTeamNameGroup.classList.remove('hidden'); }
function hideManualTeamName() { manualTeamNameGroup.classList.add('hidden'); manualTeamNameInput.value = ''; }

// ============================================================
// VALIDATION
// ============================================================
function validateForm() {
  let isValid = true;
  clearErrors();

  // District
  if (!districtSelect.value) {
    showFieldError('districtError', 'districtSelect');
    isValid = false;
  }

  if (currentCampType === 'Regular Camp') {
    // Coordinator name
    if (!coordinatorInput.value.trim()) {
      showFieldError('coordinatorError', 'coordinatorName');
      isValid = false;
    }
  } else {
    // JAS/MAS
    if (!jasMasSelect.value) {
      showFieldError('jasMasError', 'jasMasSelect');
      isValid = false;
    } else if (jasMasSelect.value === '__NOT_AVAILABLE__') {
      if (!manualJasMasInput.value.trim()) {
        showFieldError('manualJasMasError', 'manualJasMas');
        isValid = false;
      }
      if (!manualTeamNoInput.value.trim()) {
        showFieldError('manualTeamNoError', 'manualTeamNo');
        isValid = false;
      }
      if (!manualTeamNameInput.value.trim()) {
        showFieldError('manualTeamNameError', 'manualTeamName');
        isValid = false;
      }
    } else {
      // Team No
      if (!teamNoSelect.value) {
        showFieldError('teamNoError', 'teamNoSelect');
        isValid = false;
      } else if (teamNoSelect.value === '__NOT_AVAILABLE__') {
        if (!manualTeamNoInput.value.trim()) {
          showFieldError('manualTeamNoError', 'manualTeamNo');
          isValid = false;
        }
        if (!manualTeamNameInput.value.trim()) {
          showFieldError('manualTeamNameError', 'manualTeamName');
          isValid = false;
        }
      }
    }
  }

  // Consumable: mandatory fields (> 0) + no negative values
  let hasNegative = false;
  let missingOpening = false;
  let missingReceived = false;

  consumableItems.forEach(function(_, idx) {
    const openingInp  = document.getElementById('opening_' + idx);
    const receivedInp = document.getElementById('received_' + idx);
    const closingInp  = document.getElementById('closing_' + idx);

    [openingInp, receivedInp, closingInp].forEach(function(inp) {
      if (inp && inp.value !== '' && parseFloat(inp.value) < 0) {
        inp.classList.add('error');
        hasNegative = true;
      }
    });

    // Opening Stock is always mandatory and must be > 0
    const openingVal = openingInp && openingInp.value !== '' ? parseFloat(openingInp.value) : NaN;
    if (!openingInp || openingInp.value === '' || isNaN(openingVal) || openingVal <= 0) {
      if (openingInp) openingInp.classList.add('error');
      missingOpening = true;
    }

    // Received Stock is mandatory and must be > 0 only while the toggle is ON
    if (receivedClosingRequired) {
      const receivedVal = receivedInp && receivedInp.value !== '' ? parseFloat(receivedInp.value) : NaN;
      if (!receivedInp || receivedInp.value === '' || isNaN(receivedVal) || receivedVal <= 0) {
        if (receivedInp) receivedInp.classList.add('error');
        missingReceived = true;
      }
    }
  });

  if (missingOpening || missingReceived) {
    let msg = 'Please enter a value greater than 0 in ';
    if (missingOpening && missingReceived) {
      msg += 'Opening Stock and Received Stock';
    } else if (missingOpening) {
      msg += 'Opening Stock';
    } else {
      msg += 'Received Stock';
    }
    msg += ' for every consumable item.';
    if (consumableErrorEl) {
      consumableErrorEl.textContent = msg;
      consumableErrorEl.classList.add('visible');
    }
    isValid = false;
  }

  if (hasNegative) {
    showAlert('Negative values are not allowed in the consumable table. Please correct them.', 'error');
    isValid = false;
  }

  return isValid;
}

function showFieldError(errorId, inputId) {
  const errEl = document.getElementById(errorId);
  if (errEl) errEl.classList.add('visible');
  const inpEl = document.getElementById(inputId);
  if (inpEl) inpEl.classList.add('error');
}

function clearErrors() {
  document.querySelectorAll('.field-error').forEach(function(el) { el.classList.remove('visible'); });
  document.querySelectorAll('.form-control.error, select.error, input.error').forEach(function(el) { el.classList.remove('error'); });
  hideAlert('error');
}

// ============================================================
// COLLECT FORM DATA
// ============================================================
function collectFormData() {
  const now = new Date();
  const timestamp = now.toISOString().replace('T', ' ').substring(0, 19);

  // Determine JAS/MAS name, Team No, Team Name based on selections
  let jasMasName = '';
  let teamNo = '';
  let teamName = '';

  if (currentCampType !== 'Regular Camp') {
    if (jasMasSelect.value === '__NOT_AVAILABLE__') {
      jasMasName = manualJasMasInput.value.trim();
      teamNo     = manualTeamNoInput.value.trim();
      teamName   = manualTeamNameInput.value.trim();
    } else {
      jasMasName = jasMasSelect.value;
      if (teamNoSelect.value === '__NOT_AVAILABLE__') {
        teamNo   = manualTeamNoInput.value.trim();
        teamName = manualTeamNameInput.value.trim();
      } else {
        teamNo   = teamNoSelect.value;
        teamName = teamNameHidden.value;
      }
    }
  }

  // Consumable stocks
  const consumableData = consumableItems.map(function(item, idx) {
    return {
      item:    item,
      opening: parseStockVal(document.getElementById('opening_' + idx)),
      received: parseStockVal(document.getElementById('received_' + idx)),
      closing:  parseStockVal(document.getElementById('closing_' + idx))
    };
  });

  return {
    timestamp:               timestamp,
    district:                districtSelect.value,
    campType:                currentCampType,
    jasMasName:              jasMasName,
    coordinatorName:         coordinatorInput.value.trim(),
    teamNo:                  teamNo,
    teamName:                teamName,
    consumables:             consumableData,
    remarks:                 document.getElementById('remarks').value.trim()
  };
}

function parseStockVal(inp) {
  if (!inp || inp.value === '' || inp.value === null) return 0;
  const v = parseFloat(inp.value);
  return isNaN(v) || v < 0 ? 0 : v;
}

// ============================================================
// SUBMIT HANDLER
// ============================================================
function handleSubmit(e) {
  e.preventDefault();

  if (isSubmitting) return;
  if (!validateForm()) {
    // Scroll to first error
    const firstError = document.querySelector('.field-error.visible, .alert-error.visible');
    if (firstError) firstError.scrollIntoView({ behavior: 'smooth', block: 'center' });
    return;
  }

  const formData = collectFormData();
  isSubmitting = true;
  setLoading(true, 'Submitting your data to Google Sheets…');

  // Check if URL is configured
  if (!GOOGLE_SCRIPT_URL || GOOGLE_SCRIPT_URL === 'YOUR_GOOGLE_APPS_SCRIPT_URL_HERE') {
    setLoading(false);
    isSubmitting = false;
    showAlert('Configuration Error: Google Apps Script URL is not set. Please follow the deployment guide.', 'error');
    return;
  }

  // Send to Google Apps Script
  fetch(GOOGLE_SCRIPT_URL, {
    method: 'POST',
    mode: 'no-cors',
    headers: { 'Content-Type': 'text/plain' },
    body: JSON.stringify(formData)
  })
  .then(function() {
    setLoading(false);
    isSubmitting = false;
    showSuccess(formData);
  })
  .catch(function(err) {
    setLoading(false);
    isSubmitting = false;
    console.error('Submission error:', err);
    showAlert('Submission failed. Please check your internet connection and try again.', 'error');
  });
}

// ============================================================
// UI STATE HELPERS
// ============================================================
function setLoading(show, message) {
  if (show) {
    loadingMsg.textContent = message || 'Please wait…';
    loadingOverlay.classList.add('visible');
    submitBtn.disabled = true;
    submitBtn.classList.add('loading');
  } else {
    loadingOverlay.classList.remove('visible');
    submitBtn.disabled = false;
    submitBtn.classList.remove('loading');
  }
}

function showSuccess(data) {
  const refId = 'CV-' + Date.now().toString(36).toUpperCase();
  refIdDisplay.textContent = 'Reference ID: ' + refId;
  formWrapper.classList.add('hidden');
  successCard.classList.add('visible');
  successCard.scrollIntoView({ behavior: 'smooth' });
}

function showAlert(message, type) {
  if (type === 'error') {
    alertErrorMsg.textContent = message;
    alertError.classList.add('visible');
    alertError.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  }
}

function hideAlert(type) {
  if (type === 'error') alertError.classList.remove('visible');
}

// ============================================================
// RESET FORM
// ============================================================
function resetForm() {
  mainForm.reset();
  currentCampType = 'Regular Camp';
  campTypeHidden.value = 'Regular Camp';

  // Reset camp tabs
  document.querySelectorAll('.camp-tab').forEach(function(t) { t.classList.remove('active'); });
  const defaultTab = document.querySelector('.camp-tab[data-value="Regular Camp"]');
  if (defaultTab) defaultTab.classList.add('active');

  regularSection.classList.remove('hidden');
  dependentSection.classList.add('hidden');

  jasMasSelect.innerHTML = '<option value="">— Select District &amp; Camp Type first —</option>';
  jasMasSelect.disabled = true;
  teamNoSelect.innerHTML = '<option value="">— Select JAS / MAS Name first —</option>';
  teamNoSelect.disabled = true;
  resetTeamName();

  hideManualJasMas();
  hideManualTeamNo();
  hideManualTeamName();

  clearErrors();
  buildConsumableTable();

  if (trackToggle) trackToggle.checked = true;
  setReceivedClosingVisibility(true);

  isSubmitting = false;

  successCard.classList.remove('visible');
  formWrapper.classList.remove('hidden');
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

// ============================================================
// UTILITIES
// ============================================================
function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
